export type Industry =
  | "SaaS"
  | "E-commerce"
  | "Agency"
  | "Healthcare"
  | "Education"
  | "Finance"
  | "Real Estate"
  | "General";

export type TestimonialLength = "short" | "medium";

export interface Testimonial {
  id: number;
  text: string;
  author: string;
  role: string;
  company: string;
  industry: Industry;
  length: TestimonialLength;
}

export const industries: Industry[] = [
  "SaaS",
  "E-commerce",
  "Agency",
  "Healthcare",
  "Education",
  "Finance",
  "Real Estate",
  "General",
];

export const testimonials: Testimonial[] = [
  // ─── SaaS (Short) ───
  {
    id: 1,
    text: "Cut our onboarding time in half. The team was productive from day one.",
    author: "Sarah Mitchell",
    role: "VP of Operations",
    company: "CloudSync",
    industry: "SaaS",
    length: "short",
  },
  {
    id: 2,
    text: "Finally, a tool that actually delivers on its promises. Our churn dropped 23% in 3 months.",
    author: "James Park",
    role: "Head of Customer Success",
    company: "MetricFlow",
    industry: "SaaS",
    length: "short",
  },
  {
    id: 3,
    text: "Replaced 3 tools with one. Saved us $2,400/month and a lot of headaches.",
    author: "Lisa Chen",
    role: "CTO",
    company: "Stackbase",
    industry: "SaaS",
    length: "short",
  },
  {
    id: 4,
    text: "The integration took 15 minutes, not the 2 weeks we expected. Genuinely impressed.",
    author: "Mark Stevens",
    role: "Engineering Lead",
    company: "DataPipe",
    industry: "SaaS",
    length: "short",
  },
  {
    id: 5,
    text: "Our support tickets dropped 40% after implementing this. Customers find answers on their own now.",
    author: "Rachel Torres",
    role: "Head of Support",
    company: "HelpDesk Pro",
    industry: "SaaS",
    length: "short",
  },
  {
    id: 6,
    text: "Best ROI of any tool in our stack. Paid for itself in the first week.",
    author: "David Kim",
    role: "CEO",
    company: "LaunchPad AI",
    industry: "SaaS",
    length: "short",
  },
  {
    id: 7,
    text: "We tried 5 competitors before landing here. Nothing else came close.",
    author: "Amanda Foster",
    role: "Product Manager",
    company: "GrowthOS",
    industry: "SaaS",
    length: "short",
  },
  // ─── SaaS (Medium) ───
  {
    id: 8,
    text: "We were spending 12 hours a week on manual reporting. Now it takes 20 minutes. The automated dashboards give our leadership exactly what they need without anyone lifting a finger.",
    author: "Brian Walsh",
    role: "Director of Analytics",
    company: "InsightHub",
    industry: "SaaS",
    length: "medium",
  },
  {
    id: 9,
    text: "I was skeptical about switching from our old system. But after the migration, our team's productivity jumped noticeably. The learning curve was practically zero — everyone was comfortable within a day.",
    author: "Jennifer Liu",
    role: "VP of Engineering",
    company: "CodeStream",
    industry: "SaaS",
    length: "medium",
  },
  {
    id: 10,
    text: "The customer support alone makes it worth it. Every time we had a question, we got a thoughtful response within minutes. It's rare to find a company that actually cares about its users this much.",
    author: "Tom Harrison",
    role: "Operations Manager",
    company: "Relay",
    industry: "SaaS",
    length: "medium",
  },

  // ─── E-commerce (Short) ───
  {
    id: 11,
    text: "Our conversion rate went up 18% in the first month. The product basically pays for itself.",
    author: "Nicole Adams",
    role: "E-commerce Manager",
    company: "Urban Threads",
    industry: "E-commerce",
    length: "short",
  },
  {
    id: 12,
    text: "Shipping was fast, quality exceeded expectations. Already ordered again.",
    author: "Michael Brown",
    role: "Customer",
    company: "FreshGear",
    industry: "E-commerce",
    length: "short",
  },
  {
    id: 13,
    text: "Best purchase I've made this year. The quality is incredible for this price point.",
    author: "Emma Wilson",
    role: "Customer",
    company: "Luxe Home",
    industry: "E-commerce",
    length: "short",
  },
  {
    id: 14,
    text: "Customer support helped me find the perfect size. Arrived in 2 days. 10/10 experience.",
    author: "Alex Rivera",
    role: "Customer",
    company: "FitWear",
    industry: "E-commerce",
    length: "short",
  },
  {
    id: 15,
    text: "Third time ordering. The consistency is what keeps me coming back.",
    author: "Sophie Turner",
    role: "Loyal Customer",
    company: "Bean & Brew",
    industry: "E-commerce",
    length: "short",
  },
  {
    id: 16,
    text: "Returned a product with zero hassle. Full refund in 24 hours. That's how you build trust.",
    author: "Chris Martinez",
    role: "Customer",
    company: "TechGadgets",
    industry: "E-commerce",
    length: "short",
  },
  {
    id: 17,
    text: "Added reviews to our product pages and saw an immediate 22% lift in add-to-cart rates.",
    author: "Diana Lee",
    role: "Marketing Director",
    company: "NaturalGlow",
    industry: "E-commerce",
    length: "short",
  },
  // ─── E-commerce (Medium) ───
  {
    id: 18,
    text: "I was hesitant to order online but the detailed product photos and reviews convinced me. When it arrived, it looked exactly like the pictures. The packaging was beautiful too — felt like a gift.",
    author: "Patricia Moore",
    role: "Customer",
    company: "Artisan Home",
    industry: "E-commerce",
    length: "medium",
  },
  {
    id: 19,
    text: "We switched our entire product display to this platform and saw revenue increase 31% quarter over quarter. The built-in A/B testing for product layouts alone was worth the investment.",
    author: "Kevin O'Brien",
    role: "Head of E-commerce",
    company: "SportsPeak",
    industry: "E-commerce",
    length: "medium",
  },

  // ─── Agency (Short) ───
  {
    id: 20,
    text: "They delivered in 2 weeks what our previous agency couldn't do in 3 months.",
    author: "Robert Taylor",
    role: "Founder",
    company: "Nexus Ventures",
    industry: "Agency",
    length: "short",
  },
  {
    id: 21,
    text: "Finally, a team that understands both design and conversion. Our leads tripled.",
    author: "Maria Gonzalez",
    role: "VP of Marketing",
    company: "ScaleUp",
    industry: "Agency",
    length: "short",
  },
  {
    id: 22,
    text: "Working with them doesn't feel like working with an agency. It feels like having an in-house team.",
    author: "Dan Cooper",
    role: "CEO",
    company: "BrightPath",
    industry: "Agency",
    length: "short",
  },
  {
    id: 23,
    text: "They didn't just execute our brief — they challenged it and made it better.",
    author: "Olivia White",
    role: "Marketing Director",
    company: "Elevate Co",
    industry: "Agency",
    length: "short",
  },
  {
    id: 24,
    text: "ROI was visible within the first campaign. We've been working together for 2 years now.",
    author: "Steve Nguyen",
    role: "Growth Lead",
    company: "Momentum",
    industry: "Agency",
    length: "short",
  },
  {
    id: 25,
    text: "Clear communication, on-time delivery, and results that speak for themselves.",
    author: "Karen Phillips",
    role: "COO",
    company: "TrueNorth",
    industry: "Agency",
    length: "short",
  },
  // ─── Agency (Medium) ───
  {
    id: 26,
    text: "We hired them for a website redesign and ended up keeping them for everything — SEO, content, paid ads. Their strategic thinking is what sets them apart. They don't just do what you ask; they figure out what you actually need.",
    author: "Jonathan Reed",
    role: "Founder & CEO",
    company: "Atlas Digital",
    industry: "Agency",
    length: "medium",
  },
  {
    id: 27,
    text: "After working with three agencies that over-promised and under-delivered, we were skeptical. But this team backed up every claim with data. Our organic traffic grew 150% in 6 months.",
    author: "Angela Foster",
    role: "Head of Growth",
    company: "Kinetic",
    industry: "Agency",
    length: "medium",
  },

  // ─── Healthcare (Short) ───
  {
    id: 28,
    text: "Patient scheduling used to be a nightmare. Now it runs itself. We saved 15 hours a week.",
    author: "Dr. Sarah Patel",
    role: "Practice Owner",
    company: "Riverside Medical",
    industry: "Healthcare",
    length: "short",
  },
  {
    id: 29,
    text: "HIPAA-compliant and actually easy to use. Our staff adopted it without any training.",
    author: "Mike Thompson",
    role: "IT Director",
    company: "CarePoint Health",
    industry: "Healthcare",
    length: "short",
  },
  {
    id: 30,
    text: "Our patient satisfaction scores increased 35% after switching. The difference was immediate.",
    author: "Dr. Emily Zhang",
    role: "Chief Medical Officer",
    company: "Wellness First",
    industry: "Healthcare",
    length: "short",
  },
  {
    id: 31,
    text: "Patients actually leave reviews now because the process is so simple. Our online reputation transformed.",
    author: "Nancy Clark",
    role: "Practice Manager",
    company: "Smile Dental",
    industry: "Healthcare",
    length: "short",
  },
  {
    id: 32,
    text: "Reduced no-shows by 45% with automated reminders. Best investment we've made this year.",
    author: "Dr. James Monroe",
    role: "Clinic Director",
    company: "Metro Health",
    industry: "Healthcare",
    length: "short",
  },
  // ─── Healthcare (Medium) ───
  {
    id: 33,
    text: "As a small practice, we needed something affordable that didn't compromise on compliance. This solution checked every box. Our billing errors dropped to nearly zero, and we can finally focus on patient care instead of paperwork.",
    author: "Dr. Linda Morrison",
    role: "Family Physician",
    company: "Harmony Health",
    industry: "Healthcare",
    length: "medium",
  },
  {
    id: 34,
    text: "The telemedicine feature alone was worth it. During flu season, we handled 40% more patients without adding staff. Our patients love the convenience, and our team loves the efficiency.",
    author: "Rebecca Stone",
    role: "Operations Director",
    company: "ClearView Medical",
    industry: "Healthcare",
    length: "medium",
  },

  // ─── Education (Short) ───
  {
    id: 35,
    text: "Student engagement went up 40% once we started using this platform. The difference was obvious.",
    author: "Prof. Alan Wright",
    role: "Department Head",
    company: "Westfield University",
    industry: "Education",
    length: "short",
  },
  {
    id: 36,
    text: "The course changed my career. I landed a new job within 3 weeks of completing it.",
    author: "Jessica Morales",
    role: "Student",
    company: "SkillBridge Academy",
    industry: "Education",
    length: "short",
  },
  {
    id: 37,
    text: "Best online learning experience I've had. The instructors actually respond and care.",
    author: "Ryan Cooper",
    role: "Student",
    company: "LearnFlow",
    industry: "Education",
    length: "short",
  },
  {
    id: 38,
    text: "We reduced administrative overhead by 60%. Teachers can focus on teaching again.",
    author: "Martha Collins",
    role: "Principal",
    company: "Bright Horizons School",
    industry: "Education",
    length: "short",
  },
  {
    id: 39,
    text: "The curriculum was practical, not theoretical. I could apply what I learned immediately.",
    author: "Tyler Bennett",
    role: "Graduate",
    company: "TechAcademy",
    industry: "Education",
    length: "short",
  },
  // ─── Education (Medium) ───
  {
    id: 40,
    text: "We evaluated a dozen LMS platforms before choosing this one. The combination of ease of use for students and powerful analytics for instructors made it the clear winner. Our course completion rates improved from 45% to 78%.",
    author: "Dr. Samantha Lee",
    role: "Dean of Online Learning",
    company: "Pacific Institute",
    industry: "Education",
    length: "medium",
  },

  // ─── Finance (Short) ───
  {
    id: 41,
    text: "Saved us from a costly compliance mistake. The ROI was immediate and significant.",
    author: "Andrew Wright",
    role: "CFO",
    company: "Pinnacle Financial",
    industry: "Finance",
    length: "short",
  },
  {
    id: 42,
    text: "Our monthly close went from 10 days to 3. The automation is a game-changer.",
    author: "Sandra Kim",
    role: "Controller",
    company: "Summit Partners",
    industry: "Finance",
    length: "short",
  },
  {
    id: 43,
    text: "Clear, honest advice. No hidden fees. They actually want you to succeed.",
    author: "Peter Graham",
    role: "Small Business Owner",
    company: "Graham & Co",
    industry: "Finance",
    length: "short",
  },
  {
    id: 44,
    text: "Best financial advisor I've worked with. They explained everything in plain English.",
    author: "Laura Simmons",
    role: "Client",
    company: "WealthPath",
    industry: "Finance",
    length: "short",
  },
  {
    id: 45,
    text: "Helped us secure Series B funding. Their financial modeling was flawless.",
    author: "Tony Russo",
    role: "CEO",
    company: "Spark Ventures",
    industry: "Finance",
    length: "short",
  },
  // ─── Finance (Medium) ───
  {
    id: 46,
    text: "After years of juggling spreadsheets and manual reconciliations, switching to this platform was transformative. Our finance team went from working weekends during close to finishing by Wednesday. The accuracy improvement alone justified the investment.",
    author: "Michelle Davis",
    role: "VP of Finance",
    company: "Apex Capital",
    industry: "Finance",
    length: "medium",
  },

  // ─── Real Estate (Short) ───
  {
    id: 47,
    text: "Sold our house in 5 days, above asking price. Could not have asked for a better agent.",
    author: "David & Sarah Johnson",
    role: "Home Sellers",
    company: "Premier Realty",
    industry: "Real Estate",
    length: "short",
  },
  {
    id: 48,
    text: "Found our dream home on the first viewing. They really listened to what we wanted.",
    author: "Maria Santos",
    role: "Home Buyer",
    company: "Keystone Properties",
    industry: "Real Estate",
    length: "short",
  },
  {
    id: 49,
    text: "The virtual tours saved us 20+ hours of house hunting. Game-changer for busy professionals.",
    author: "Greg Palmer",
    role: "Buyer",
    company: "NextHome Digital",
    industry: "Real Estate",
    length: "short",
  },
  {
    id: 50,
    text: "Managed our rental properties for 3 years. Zero vacancies. Highly recommend.",
    author: "Angela Washington",
    role: "Property Investor",
    company: "Horizon Property Mgmt",
    industry: "Real Estate",
    length: "short",
  },
  {
    id: 51,
    text: "They negotiated $30K off the listing price. Best decision was hiring them as our buyer's agent.",
    author: "Chris & Amy Lee",
    role: "Home Buyers",
    company: "City Living Realty",
    industry: "Real Estate",
    length: "short",
  },
  // ─── Real Estate (Medium) ───
  {
    id: 52,
    text: "As first-time buyers, we were overwhelmed by the process. Our agent walked us through every step, from mortgage pre-approval to closing. They were available nights and weekends, and we never felt rushed into a decision.",
    author: "Jason & Emily Park",
    role: "First-time Buyers",
    company: "HomeFinder Realty",
    industry: "Real Estate",
    length: "medium",
  },

  // ─── General (Short) ───
  {
    id: 53,
    text: "Exceeded every expectation. Will definitely be using them again.",
    author: "Michael Torres",
    role: "Director",
    company: "Atlas Group",
    industry: "General",
    length: "short",
  },
  {
    id: 54,
    text: "Responsive, professional, and delivered ahead of schedule. A rare combination.",
    author: "Laura Chen",
    role: "VP of Operations",
    company: "Velocity Inc",
    industry: "General",
    length: "short",
  },
  {
    id: 55,
    text: "Transformed how our team works. The impact was visible within the first week.",
    author: "Robert Kim",
    role: "Team Lead",
    company: "Forge Solutions",
    industry: "General",
    length: "short",
  },
  {
    id: 56,
    text: "Simple, effective, and worth every penny. Wish we had found this sooner.",
    author: "Hannah Patel",
    role: "Manager",
    company: "Bright Co",
    industry: "General",
    length: "short",
  },
  {
    id: 57,
    text: "They solved in one call what we'd been struggling with for months.",
    author: "Derek Johnson",
    role: "Founder",
    company: "Launchpad Studios",
    industry: "General",
    length: "short",
  },
  {
    id: 58,
    text: "I recommend them to every business owner I know. Zero regrets.",
    author: "Samantha Blake",
    role: "CEO",
    company: "NorthStar Media",
    industry: "General",
    length: "short",
  },
  {
    id: 59,
    text: "The attention to detail was exceptional. You can tell they take pride in their work.",
    author: "William Grant",
    role: "Creative Director",
    company: "Prism Agency",
    industry: "General",
    length: "short",
  },
  // ─── General (Medium) ───
  {
    id: 60,
    text: "We've worked with dozens of vendors over the years, and this experience stands out. They were transparent about timelines, proactive about potential issues, and delivered a result that our entire team was excited about.",
    author: "Catherine Moore",
    role: "Chief Operating Officer",
    company: "Elevate Partners",
    industry: "General",
    length: "medium",
  },
  {
    id: 61,
    text: "From the first call to the final delivery, everything was smooth. They asked the right questions upfront, kept us updated throughout, and the end result exceeded what we had in mind.",
    author: "Marcus Bell",
    role: "Head of Procurement",
    company: "Summit Enterprises",
    industry: "General",
    length: "medium",
  },
  {
    id: 62,
    text: "What impressed me most wasn't just the quality of work — it was how easy they made the process. Clear communication, no surprises, and a team that genuinely wanted us to succeed.",
    author: "Rachel Foster",
    role: "Program Director",
    company: "ImpactWorks",
    industry: "General",
    length: "medium",
  },
];
