export interface FormTemplate {
  id: number;
  type: "short-form" | "detailed-form" | "video-prompt" | "nps-followup" | "case-study";
  industry: string;
  questionCount: number;
  title: string;
  description: string;
  questions: string[];
}

export const formTypes = [
  "All Types",
  "Short Form (3-5 questions)",
  "Detailed Form (6-10 questions)",
  "Video Prompt Questions",
  "NPS Follow-Up",
  "Case Study Questions",
] as const;

export const formTypeMap: Record<string, FormTemplate["type"] | null> = {
  "All Types": null,
  "Short Form (3-5 questions)": "short-form",
  "Detailed Form (6-10 questions)": "detailed-form",
  "Video Prompt Questions": "video-prompt",
  "NPS Follow-Up": "nps-followup",
  "Case Study Questions": "case-study",
};

export const industries = [
  "All Industries",
  "SaaS",
  "E-commerce",
  "Agency",
  "Healthcare",
  "Real Estate",
  "Fitness",
  "Restaurant",
  "Professional Services",
  "Education",
  "Consulting",
] as const;

export const typeColors: Record<FormTemplate["type"], string> = {
  "short-form": "bg-blue-50 text-blue-600",
  "detailed-form": "bg-purple-50 text-purple-600",
  "video-prompt": "bg-rose-50 text-rose-600",
  "nps-followup": "bg-amber-50 text-amber-600",
  "case-study": "bg-emerald-50 text-emerald-700",
};

export const typeLabels: Record<FormTemplate["type"], string> = {
  "short-form": "Short Form",
  "detailed-form": "Detailed Form",
  "video-prompt": "Video Prompt",
  "nps-followup": "NPS Follow-Up",
  "case-study": "Case Study",
};

export const templates: FormTemplate[] = [
  // ===== SaaS =====
  {
    id: 1,
    type: "short-form",
    industry: "SaaS",
    questionCount: 4,
    title: "SaaS Quick Testimonial",
    description: "Fast testimonial form for SaaS users after onboarding or a support win.",
    questions: [
      "What problem were you trying to solve before using our product?",
      "How has our product helped you solve that problem?",
      "What specific feature do you find most valuable?",
      "Would you recommend us to a colleague? Why?",
    ],
  },
  {
    id: 2,
    type: "detailed-form",
    industry: "SaaS",
    questionCount: 8,
    title: "SaaS Customer Success Story",
    description: "In-depth form for capturing detailed SaaS testimonials with metrics and outcomes.",
    questions: [
      "What was your biggest challenge before using our product?",
      "What other solutions did you evaluate before choosing us?",
      "How was your onboarding experience?",
      "What measurable results have you seen since using our product?",
      "How much time or money has our product saved you?",
      "Which feature has had the biggest impact on your workflow?",
      "How would you describe our product to someone in your role?",
      "What would you say to someone considering our product?",
    ],
  },
  {
    id: 3,
    type: "video-prompt",
    industry: "SaaS",
    questionCount: 5,
    title: "SaaS Video Testimonial Prompts",
    description: "Guided video prompts to help SaaS customers record natural-sounding testimonials.",
    questions: [
      "Tell us your name, your role, and what your company does.",
      "What was your biggest pain point before you started using our tool?",
      "Walk us through how you use the product day-to-day.",
      "What results have you seen since switching to our product?",
      "What would you tell someone who is on the fence about trying it?",
    ],
  },
  {
    id: 4,
    type: "nps-followup",
    industry: "SaaS",
    questionCount: 4,
    title: "SaaS NPS Promoter Follow-Up",
    description: "Follow-up form for NPS promoters (9-10) to turn their score into a usable testimonial.",
    questions: [
      "You gave us a high score — what is the main reason you would recommend us?",
      "What specific outcome or improvement have you experienced?",
      "Is there a particular moment when you realized our product was worth it?",
      "Can we share your response as a testimonial on our website? (with your name and company)",
    ],
  },
  {
    id: 5,
    type: "case-study",
    industry: "SaaS",
    questionCount: 10,
    title: "SaaS Case Study Interview",
    description: "Comprehensive case study questionnaire covering the full before/after journey.",
    questions: [
      "Tell us about your company and your role.",
      "What challenges or goals led you to look for a solution?",
      "What was your process like before using our product?",
      "How did you discover our product and what made you choose it?",
      "Describe your onboarding and implementation experience.",
      "What does your day-to-day look like now with our product?",
      "What quantifiable results have you achieved? (time saved, revenue, efficiency)",
      "How has our product impacted your team or organization?",
      "What would you say to someone evaluating our product?",
      "Is there anything else you would like to share about your experience?",
    ],
  },

  // ===== E-commerce =====
  {
    id: 6,
    type: "short-form",
    industry: "E-commerce",
    questionCount: 4,
    title: "Product Review Request",
    description: "Quick post-purchase form to capture product-specific testimonials.",
    questions: [
      "What did you purchase and why did you choose it?",
      "How would you rate the quality of the product?",
      "What do you like most about it?",
      "Would you recommend this product to a friend?",
    ],
  },
  {
    id: 7,
    type: "detailed-form",
    industry: "E-commerce",
    questionCount: 7,
    title: "E-commerce Customer Experience Survey",
    description: "End-to-end feedback form covering product, shipping, and overall experience.",
    questions: [
      "What product(s) did you order and what made you choose our store?",
      "How was your shopping experience on our website?",
      "How would you describe the packaging and delivery?",
      "Does the product meet your expectations? Why or why not?",
      "How does this product compare to similar ones you have tried?",
      "What would you tell someone considering buying from us?",
      "Is there anything we could improve?",
    ],
  },
  {
    id: 8,
    type: "video-prompt",
    industry: "E-commerce",
    questionCount: 4,
    title: "Unboxing & Review Video Prompts",
    description: "Prompts for customers to record authentic product unboxing and review videos.",
    questions: [
      "Show us the product and tell us what you ordered.",
      "What was your first impression when you opened the package?",
      "How have you been using the product and what do you think of the quality?",
      "Would you buy from us again? Who would you recommend this to?",
    ],
  },
  {
    id: 9,
    type: "nps-followup",
    industry: "E-commerce",
    questionCount: 3,
    title: "E-commerce NPS Promoter Form",
    description: "Quick follow-up for happy customers who scored 9-10 on NPS surveys.",
    questions: [
      "What is the main reason you would recommend our store to others?",
      "Which product has been your favorite purchase from us?",
      "Can we use your feedback as a testimonial? (with first name and city)",
    ],
  },

  // ===== Agency =====
  {
    id: 10,
    type: "short-form",
    industry: "Agency",
    questionCount: 4,
    title: "Agency Client Quick Feedback",
    description: "Short form for agency clients after a project milestone or delivery.",
    questions: [
      "What did we help you with?",
      "What results have you seen from our work together?",
      "How would you describe working with our team?",
      "Would you recommend our agency? Why?",
    ],
  },
  {
    id: 11,
    type: "detailed-form",
    industry: "Agency",
    questionCount: 8,
    title: "Agency Client Testimonial Survey",
    description: "Detailed testimonial form to capture the full scope of an agency engagement.",
    questions: [
      "What was the challenge or goal that brought you to our agency?",
      "What other options did you consider before working with us?",
      "How was the onboarding and kickoff process?",
      "Describe the communication and collaboration throughout the project.",
      "What results or deliverables exceeded your expectations?",
      "How has our work impacted your business metrics?",
      "What makes our agency different from others you have worked with?",
      "What would you tell a peer who is looking for a similar agency?",
    ],
  },
  {
    id: 12,
    type: "case-study",
    industry: "Agency",
    questionCount: 9,
    title: "Agency Case Study Questionnaire",
    description: "Full case study form for agency clients to document the engagement journey.",
    questions: [
      "Tell us about your company, industry, and target audience.",
      "What was the business problem or opportunity you needed help with?",
      "What had you tried before working with us?",
      "Why did you choose our agency over alternatives?",
      "Walk us through the project scope and timeline.",
      "What specific results did the engagement deliver?",
      "Can you share any numbers — revenue, leads, traffic, conversions?",
      "How would you describe the collaboration and communication?",
      "What advice would you give to someone considering hiring our agency?",
    ],
  },
  {
    id: 13,
    type: "video-prompt",
    industry: "Agency",
    questionCount: 4,
    title: "Agency Client Video Testimonial",
    description: "Simple video prompts for agency clients to record a quick recommendation.",
    questions: [
      "Introduce yourself and your company in one sentence.",
      "What did our agency help you accomplish?",
      "What results or impact did you see from the work?",
      "What would you say to someone considering working with us?",
    ],
  },

  // ===== Healthcare =====
  {
    id: 14,
    type: "short-form",
    industry: "Healthcare",
    questionCount: 4,
    title: "Patient Experience Quick Form",
    description: "Brief patient satisfaction form for clinics and practices.",
    questions: [
      "What brought you to our practice?",
      "How would you describe your experience with our staff and providers?",
      "What stood out most about your visit?",
      "Would you recommend our practice to family or friends?",
    ],
  },
  {
    id: 15,
    type: "detailed-form",
    industry: "Healthcare",
    questionCount: 7,
    title: "Healthcare Patient Feedback Survey",
    description: "Comprehensive patient feedback form covering the full care experience.",
    questions: [
      "What condition or concern brought you to our practice?",
      "How easy was it to schedule an appointment?",
      "How would you rate the friendliness and professionalism of our staff?",
      "Did the provider take time to explain your diagnosis and treatment options?",
      "How would you describe the facility and waiting area?",
      "What has been the outcome of your treatment so far?",
      "Is there anything we could do to improve your experience?",
    ],
  },
  {
    id: 16,
    type: "nps-followup",
    industry: "Healthcare",
    questionCount: 3,
    title: "Healthcare NPS Follow-Up",
    description: "Follow-up form for patients who rated their experience highly.",
    questions: [
      "What is the main reason you would recommend our practice?",
      "Is there a specific provider or staff member you would like to recognize?",
      "May we share your feedback on our website? (first name and initial only)",
    ],
  },
  {
    id: 17,
    type: "video-prompt",
    industry: "Healthcare",
    questionCount: 4,
    title: "Patient Video Testimonial Prompts",
    description: "Video prompts for patients to share their care journey (HIPAA-friendly).",
    questions: [
      "Tell us your first name and what brought you to our practice.",
      "How was your experience with the care team?",
      "How has the treatment improved your daily life?",
      "What would you tell someone who is nervous about visiting us?",
    ],
  },

  // ===== Real Estate =====
  {
    id: 18,
    type: "short-form",
    industry: "Real Estate",
    questionCount: 4,
    title: "Real Estate Client Quick Review",
    description: "Post-closing feedback form for buyers and sellers.",
    questions: [
      "Were you buying or selling a property?",
      "How would you describe your agent's communication and availability?",
      "What was the best part of working with us?",
      "Would you recommend us to someone buying or selling a home?",
    ],
  },
  {
    id: 19,
    type: "detailed-form",
    industry: "Real Estate",
    questionCount: 7,
    title: "Real Estate Client Experience Survey",
    description: "Detailed post-transaction survey for real estate clients.",
    questions: [
      "What were your goals when you started the home buying/selling process?",
      "How did you find our agency or agent?",
      "How would you rate the communication throughout the process?",
      "Were there any challenges, and how did your agent handle them?",
      "How did the final outcome compare to your expectations?",
      "What made our service stand out from other agents you considered?",
      "What would you say to someone starting their real estate journey?",
    ],
  },
  {
    id: 20,
    type: "case-study",
    industry: "Real Estate",
    questionCount: 8,
    title: "Real Estate Success Story",
    description: "Full case study form to document a client's real estate journey.",
    questions: [
      "Tell us about yourself and what prompted your real estate transaction.",
      "What were your must-haves and deal-breakers?",
      "How did you choose your agent or brokerage?",
      "Describe the search or listing process.",
      "Were there any obstacles, and how were they overcome?",
      "What was the outcome — price, timeline, satisfaction?",
      "How did the experience compare to your expectations?",
      "What advice would you give to first-time buyers or sellers?",
    ],
  },
  {
    id: 21,
    type: "video-prompt",
    industry: "Real Estate",
    questionCount: 4,
    title: "Real Estate Video Testimonial",
    description: "Quick video prompts for clients to record after closing.",
    questions: [
      "Tell us your name and whether you bought or sold a home with us.",
      "What was the best part of working with your agent?",
      "How did the result compare to what you expected?",
      "What would you say to someone thinking about using our services?",
    ],
  },

  // ===== Fitness =====
  {
    id: 22,
    type: "short-form",
    industry: "Fitness",
    questionCount: 4,
    title: "Gym Member Quick Testimonial",
    description: "Short form for gym or studio members to share their results.",
    questions: [
      "What were your fitness goals when you joined?",
      "What results have you achieved so far?",
      "What do you enjoy most about our gym/studio?",
      "Would you recommend us to a friend? Why?",
    ],
  },
  {
    id: 23,
    type: "detailed-form",
    industry: "Fitness",
    questionCount: 7,
    title: "Fitness Transformation Survey",
    description: "Detailed form for capturing fitness transformation stories and results.",
    questions: [
      "What was your fitness level and health situation before joining?",
      "What motivated you to start your fitness journey?",
      "What programs or classes have you participated in?",
      "What physical or mental changes have you experienced?",
      "How have the trainers or staff supported your progress?",
      "What keeps you coming back?",
      "What would you tell someone who is thinking about joining but hesitant?",
    ],
  },
  {
    id: 24,
    type: "video-prompt",
    industry: "Fitness",
    questionCount: 5,
    title: "Fitness Transformation Video Prompts",
    description: "Video prompts for members to share their transformation story on camera.",
    questions: [
      "Tell us your name and how long you have been a member.",
      "What did your health and fitness look like before you joined?",
      "What changes have you seen in your body, energy, or mindset?",
      "What is your favorite thing about training here?",
      "What would you say to someone who is nervous about starting?",
    ],
  },
  {
    id: 25,
    type: "nps-followup",
    industry: "Fitness",
    questionCount: 3,
    title: "Fitness NPS Promoter Form",
    description: "Quick follow-up for members who rated their experience 9 or 10.",
    questions: [
      "What is the number one reason you would recommend our gym/studio?",
      "Is there a trainer or class you would specifically recommend?",
      "Can we share your feedback on our website and social media?",
    ],
  },

  // ===== Restaurant =====
  {
    id: 26,
    type: "short-form",
    industry: "Restaurant",
    questionCount: 4,
    title: "Restaurant Guest Feedback",
    description: "Quick post-dining form to capture guest satisfaction and recommendations.",
    questions: [
      "What did you order and how was the food?",
      "How would you describe the service and atmosphere?",
      "What was the highlight of your dining experience?",
      "Would you recommend us to friends or family?",
    ],
  },
  {
    id: 27,
    type: "detailed-form",
    industry: "Restaurant",
    questionCount: 7,
    title: "Restaurant Dining Experience Survey",
    description: "Detailed guest survey for capturing comprehensive dining feedback.",
    questions: [
      "What was the occasion for your visit?",
      "How did you hear about our restaurant?",
      "How would you rate the quality and presentation of the food?",
      "How was the service from the moment you arrived to when you left?",
      "How would you describe the ambiance and cleanliness?",
      "Was the pricing fair for the quality of the experience?",
      "What would you tell a friend who has never been to our restaurant?",
    ],
  },
  {
    id: 28,
    type: "video-prompt",
    industry: "Restaurant",
    questionCount: 3,
    title: "Restaurant Video Review Prompts",
    description: "Simple prompts for guests to record a quick video review.",
    questions: [
      "What did you have tonight and what did you think?",
      "What was the best part of your dining experience?",
      "Would you come back? Who would you bring?",
    ],
  },
  {
    id: 29,
    type: "nps-followup",
    industry: "Restaurant",
    questionCount: 3,
    title: "Restaurant NPS Follow-Up",
    description: "Follow-up for guests who gave a high satisfaction score.",
    questions: [
      "What made your experience stand out enough to recommend us?",
      "Is there a specific dish or staff member you want to highlight?",
      "May we feature your feedback on our website or social media?",
    ],
  },

  // ===== Professional Services =====
  {
    id: 30,
    type: "short-form",
    industry: "Professional Services",
    questionCount: 4,
    title: "Professional Services Client Feedback",
    description: "Quick form for law firms, accountants, and consultants after an engagement.",
    questions: [
      "What service did we provide for you?",
      "How would you describe the quality of work and communication?",
      "What outcome or result did you achieve?",
      "Would you recommend our firm to a colleague?",
    ],
  },
  {
    id: 31,
    type: "detailed-form",
    industry: "Professional Services",
    questionCount: 8,
    title: "Professional Services Client Survey",
    description: "Comprehensive feedback form for professional service engagements.",
    questions: [
      "What challenge or need prompted you to seek professional help?",
      "How did you find our firm and why did you choose us?",
      "How was the initial consultation and engagement process?",
      "How would you rate the expertise and knowledge of our team?",
      "Were deliverables completed on time and within budget?",
      "What results or outcomes did the engagement produce?",
      "How does our service compare to other firms you have worked with?",
      "What would you tell someone who needs similar services?",
    ],
  },
  {
    id: 32,
    type: "case-study",
    industry: "Professional Services",
    questionCount: 9,
    title: "Professional Services Case Study",
    description: "Full case study questionnaire for documenting professional service outcomes.",
    questions: [
      "Tell us about your organization and the context of the engagement.",
      "What was the specific problem or goal you needed help with?",
      "What had you tried before engaging our firm?",
      "Describe the scope of work and approach we took.",
      "How was the communication and project management throughout?",
      "What were the key deliverables and outcomes?",
      "Can you share any metrics that demonstrate the impact?",
      "How has the engagement affected your business long-term?",
      "What would you say to someone considering hiring our firm?",
    ],
  },
  {
    id: 33,
    type: "video-prompt",
    industry: "Professional Services",
    questionCount: 4,
    title: "Professional Services Video Testimonial",
    description: "Video prompts for professional service clients to record a recommendation.",
    questions: [
      "Introduce yourself and your organization.",
      "What did our firm help you with?",
      "What results or outcomes have you seen?",
      "Why would you recommend our firm to others?",
    ],
  },

  // ===== Education =====
  {
    id: 34,
    type: "short-form",
    industry: "Education",
    questionCount: 4,
    title: "Course/Program Quick Feedback",
    description: "Short form for students or participants after completing a course or program.",
    questions: [
      "What course or program did you complete?",
      "What was the most valuable thing you learned?",
      "How has the program impacted your career or skills?",
      "Would you recommend this program to others?",
    ],
  },
  {
    id: 35,
    type: "detailed-form",
    industry: "Education",
    questionCount: 8,
    title: "Education Program Review Survey",
    description: "Detailed form for gathering comprehensive program feedback from students.",
    questions: [
      "What program or course did you enroll in and why?",
      "What were your goals or expectations before starting?",
      "How was the quality of the curriculum and course materials?",
      "How would you rate the instructors and their teaching style?",
      "How was the support from staff and the learning community?",
      "What skills or knowledge have you gained?",
      "How has the program affected your career or personal development?",
      "What would you tell someone considering this program?",
    ],
  },
  {
    id: 36,
    type: "video-prompt",
    industry: "Education",
    questionCount: 4,
    title: "Student Video Testimonial Prompts",
    description: "Video prompts for students to share their learning experience on camera.",
    questions: [
      "Tell us your name and what program you completed.",
      "What was the most impactful thing you learned?",
      "How has the program changed your career or outlook?",
      "What would you say to someone thinking about enrolling?",
    ],
  },
  {
    id: 37,
    type: "nps-followup",
    industry: "Education",
    questionCount: 3,
    title: "Education NPS Follow-Up",
    description: "Follow-up for students who rated their experience highly.",
    questions: [
      "What is the main reason you would recommend our program?",
      "Is there a specific instructor or module that stood out?",
      "May we share your feedback on our website and marketing materials?",
    ],
  },

  // ===== Consulting =====
  {
    id: 38,
    type: "short-form",
    industry: "Consulting",
    questionCount: 4,
    title: "Consulting Client Quick Testimonial",
    description: "Short form for consulting clients to share engagement outcomes.",
    questions: [
      "What business challenge did we help you address?",
      "What was the most valuable insight or recommendation you received?",
      "What measurable impact has the engagement had?",
      "Would you engage our consulting services again? Why?",
    ],
  },
  {
    id: 39,
    type: "detailed-form",
    industry: "Consulting",
    questionCount: 8,
    title: "Consulting Engagement Feedback Survey",
    description: "Comprehensive feedback form for consulting engagements.",
    questions: [
      "What prompted you to seek consulting support?",
      "How did you select our firm from the options you considered?",
      "How was the discovery and scoping phase?",
      "Describe the quality and actionability of the recommendations.",
      "How effective was the communication throughout the engagement?",
      "What outcomes or changes resulted from the engagement?",
      "How has the engagement impacted your organization long-term?",
      "What would you tell a peer who is considering hiring a consultant?",
    ],
  },
  {
    id: 40,
    type: "case-study",
    industry: "Consulting",
    questionCount: 9,
    title: "Consulting Case Study Questionnaire",
    description: "Full case study form for documenting consulting engagement results.",
    questions: [
      "Tell us about your organization and its industry.",
      "What was the strategic challenge or opportunity?",
      "What had you tried internally before engaging us?",
      "Describe the approach and methodology we used.",
      "How was the working relationship and collaboration?",
      "What were the key recommendations and deliverables?",
      "What measurable results have you achieved since the engagement?",
      "How has the engagement influenced your strategic direction?",
      "What would you say to a CEO or founder considering consulting support?",
    ],
  },
  {
    id: 41,
    type: "video-prompt",
    industry: "Consulting",
    questionCount: 4,
    title: "Consulting Client Video Testimonial",
    description: "Video prompts for consulting clients to record a quick recommendation.",
    questions: [
      "Tell us your name, role, and company.",
      "What did our consulting team help you solve?",
      "What has changed in your business since the engagement?",
      "Who would you recommend our services to?",
    ],
  },
  {
    id: 42,
    type: "nps-followup",
    industry: "Consulting",
    questionCount: 4,
    title: "Consulting NPS Promoter Follow-Up",
    description: "Follow-up for consulting clients who scored 9-10 on NPS.",
    questions: [
      "What is the primary reason you would recommend our consulting services?",
      "Was there a specific deliverable or insight that stood out?",
      "How has the engagement impacted your team or bottom line?",
      "May we share your response as a testimonial?",
    ],
  },
];
