export interface TestimonialExample {
  id: number;
  quote: string;
  name: string;
  role: string;
  company: string;
  industry: string;
  category: string;
  length: "short" | "medium" | "long";
  stars: number;
}

export const industries = [
  "All Industries",
  "SaaS & Software",
  "E-commerce",
  "Marketing Agency",
  "Healthcare",
  "Education",
  "Financial Services",
  "Real Estate",
  "Consulting",
  "Fitness & Wellness",
  "Food & Restaurant",
  "Legal",
  "Construction & Home",
] as const;

export const categories = [
  "All Categories",
  "Product Quality",
  "Customer Support",
  "ROI & Results",
  "Ease of Use",
  "Time Savings",
  "Team Collaboration",
  "Onboarding",
  "Value for Money",
] as const;

export const lengths = [
  "All Lengths",
  "Short (1-2 sentences)",
  "Medium (3-4 sentences)",
  "Long (5+ sentences)",
] as const;

export const testimonials: TestimonialExample[] = [
  // SaaS & Software
  {
    id: 1,
    quote:
      "This tool cut our onboarding time in half. New team members are productive from day one.",
    name: "Sarah Chen",
    role: "VP of Engineering",
    company: "TechFlow",
    industry: "SaaS & Software",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  {
    id: 2,
    quote:
      "We switched from three separate tools to just this one. Saved us $2,400/month and our workflow is actually smoother now.",
    name: "Marcus Rivera",
    role: "CTO",
    company: "DataSync",
    industry: "SaaS & Software",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 3,
    quote:
      "The API documentation is the best I've ever seen. Our developers had the integration running in under an hour. The support team was incredibly responsive when we had edge case questions, and the sandbox environment made testing painless.",
    name: "Priya Patel",
    role: "Lead Developer",
    company: "BuildKit",
    industry: "SaaS & Software",
    category: "Ease of Use",
    length: "long",
    stars: 5,
  },
  {
    id: 4,
    quote:
      "Support response time went from 4 hours to 15 minutes after implementing this. Our CSAT scores jumped from 72% to 94%. The automation handles 60% of tickets without human intervention.",
    name: "James Liu",
    role: "Head of Support",
    company: "CloudBase",
    industry: "SaaS & Software",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  {
    id: 5,
    quote:
      "Finally, a dashboard that actually makes sense. I can see everything I need in one view without clicking through ten menus.",
    name: "Nina Kowalski",
    role: "Product Manager",
    company: "FlowMetrics",
    industry: "SaaS & Software",
    category: "Ease of Use",
    length: "short",
    stars: 5,
  },
  {
    id: 6,
    quote:
      "We evaluated 12 solutions. This was the only one that didn't require a dedicated admin. Setup took 20 minutes and it just works.",
    name: "Tom Bradley",
    role: "IT Director",
    company: "ScaleOps",
    industry: "SaaS & Software",
    category: "Ease of Use",
    length: "medium",
    stars: 5,
  },
  {
    id: 7,
    quote:
      "The team collaboration features changed how we work. Real-time editing, async comments, version history — it's everything we needed and nothing we didn't.",
    name: "Alex Nguyen",
    role: "Design Lead",
    company: "PixelCraft",
    industry: "SaaS & Software",
    category: "Team Collaboration",
    length: "medium",
    stars: 5,
  },
  {
    id: 8,
    quote: "Best investment we made this year. ROI was positive within 6 weeks.",
    name: "Rachel Kim",
    role: "CEO",
    company: "LaunchPad",
    industry: "SaaS & Software",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  // E-commerce
  {
    id: 9,
    quote:
      "Our conversion rate jumped 23% in the first month. The A/B testing tools made it easy to find what works.",
    name: "David Park",
    role: "E-commerce Manager",
    company: "StyleHouse",
    industry: "E-commerce",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 10,
    quote:
      "Shipping was incredibly fast — got my order in 2 days. The packaging was beautiful and the product exceeded my expectations. Will definitely order again.",
    name: "Emma Thompson",
    role: "Customer",
    company: "GreenLeaf",
    industry: "E-commerce",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 11,
    quote:
      "I was skeptical about ordering online, but the customer service team walked me through everything. When my first order had an issue, they resolved it within an hour and sent a replacement overnight. That level of care earned a customer for life.",
    name: "Maria Santos",
    role: "Customer",
    company: "LuxCraft",
    industry: "E-commerce",
    category: "Customer Support",
    length: "long",
    stars: 5,
  },
  {
    id: 12,
    quote:
      "The product recommendation engine increased our average order value by 31%. It practically pays for itself.",
    name: "Jake Morrison",
    role: "Head of Growth",
    company: "TrendMart",
    industry: "E-commerce",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 13,
    quote:
      "Setup was painless. We migrated from Shopify in a weekend and didn't lose a single order.",
    name: "Lisa Wang",
    role: "Operations Lead",
    company: "FreshBox",
    industry: "E-commerce",
    category: "Ease of Use",
    length: "short",
    stars: 5,
  },
  {
    id: 14,
    quote:
      "Quality is outstanding for the price point. I've compared with brands charging 3x more and honestly can't tell the difference.",
    name: "Ryan Foster",
    role: "Customer",
    company: "PeakGear",
    industry: "E-commerce",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 15,
    quote:
      "The inventory management alone saved us 15 hours per week. Add the automated reordering and we've basically eliminated stockouts.",
    name: "Hannah Lee",
    role: "Supply Chain Manager",
    company: "UrbanBasics",
    industry: "E-commerce",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 16,
    quote:
      "Our return rate dropped from 12% to 4% after implementing the size recommendation tool. Customers are happier, and we're saving thousands on return shipping.",
    name: "Chris Anderson",
    role: "CEO",
    company: "FitWear",
    industry: "E-commerce",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  // Marketing Agency
  {
    id: 17,
    quote:
      "They doubled our organic traffic in 90 days. No fluff, no BS — just results we can see in our revenue.",
    name: "Ben Torres",
    role: "Founder",
    company: "GrowthLab",
    industry: "Marketing Agency",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 18,
    quote:
      "The reporting alone is worth the investment. Clients love the dashboards and I spend 80% less time on manual report creation.",
    name: "Amy Zhang",
    role: "Account Director",
    company: "BrightMedia",
    industry: "Marketing Agency",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 19,
    quote:
      "We've worked with five agencies over the past three years. This is the first one that actually listens. They adjusted our strategy based on real data, not just gut feelings. Our CAC dropped 40% and lead quality improved significantly.",
    name: "Sandra Mitchell",
    role: "CMO",
    company: "NexGen Solutions",
    industry: "Marketing Agency",
    category: "ROI & Results",
    length: "long",
    stars: 5,
  },
  {
    id: 20,
    quote:
      "From pitch to execution in 2 weeks. Most agencies take months to get started. These guys move fast.",
    name: "Kevin O'Brien",
    role: "Marketing Director",
    company: "SparkBrand",
    industry: "Marketing Agency",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  {
    id: 21,
    quote:
      "The team feels like an extension of our own. Weekly syncs, Slack availability, proactive suggestions. This is what partnership looks like.",
    name: "Diana Reyes",
    role: "VP of Marketing",
    company: "Elevate",
    industry: "Marketing Agency",
    category: "Team Collaboration",
    length: "medium",
    stars: 5,
  },
  {
    id: 22,
    quote:
      "Our email open rates went from 18% to 34%. Click-through doubled. Revenue from email is now our second largest channel.",
    name: "Mike Chen",
    role: "Head of Growth",
    company: "ReachOut",
    industry: "Marketing Agency",
    category: "ROI & Results",
    length: "medium",
    stars: 4,
  },
  {
    id: 23,
    quote:
      "Transparent pricing, no hidden fees, and they actually come in under budget. Refreshing in this industry.",
    name: "Lauren Adams",
    role: "CFO",
    company: "Pulse Digital",
    industry: "Marketing Agency",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 24,
    quote:
      "They turned our messy brand into something cohesive and professional. Website redesign, new copy, social templates — all delivered on time.",
    name: "Carlos Mendez",
    role: "Founder",
    company: "Visto",
    industry: "Marketing Agency",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  // Healthcare
  {
    id: 25,
    quote:
      "Patient scheduling used to be our biggest headache. Now it runs itself. No-shows dropped 35%.",
    name: "Dr. Emily Watson",
    role: "Practice Owner",
    company: "Lakewood Medical",
    industry: "Healthcare",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 26,
    quote:
      "HIPAA compliance was our top concern. Their team handled everything and we passed our audit with zero findings. The patient portal is intuitive — even our elderly patients navigate it easily.",
    name: "Dr. Robert Kim",
    role: "Medical Director",
    company: "Summit Health",
    industry: "Healthcare",
    category: "Product Quality",
    length: "long",
    stars: 5,
  },
  {
    id: 27,
    quote:
      "Staff training took less than a day. The interface is so intuitive that even our least tech-savvy team members picked it up immediately.",
    name: "Jennifer Hayes",
    role: "Office Manager",
    company: "ClearView Dental",
    industry: "Healthcare",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  {
    id: 28,
    quote:
      "The telehealth integration is seamless. Patients book, join, and follow up — all in one platform. Our virtual visit volume tripled.",
    name: "Dr. Aisha Johnson",
    role: "Physician",
    company: "HealthFirst Clinic",
    industry: "Healthcare",
    category: "Ease of Use",
    length: "medium",
    stars: 5,
  },
  {
    id: 29,
    quote:
      "Billing errors dropped 90% after switching. We recovered $45,000 in the first quarter alone from claims that would have been denied.",
    name: "Stephanie Moore",
    role: "Billing Director",
    company: "Regional Care Network",
    industry: "Healthcare",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 30,
    quote:
      "The care team loved it from day one. That never happens with new software.",
    name: "Dr. Michael Torres",
    role: "Chief of Staff",
    company: "Pacific Medical Group",
    industry: "Healthcare",
    category: "Ease of Use",
    length: "short",
    stars: 5,
  },
  {
    id: 31,
    quote:
      "Patient satisfaction scores jumped from 3.8 to 4.7 stars after we implemented the automated follow-up system.",
    name: "Karen Phillips",
    role: "Patient Experience Lead",
    company: "Wellness Partners",
    industry: "Healthcare",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 32,
    quote:
      "Support is exceptional. When our system went down during flu season, their team had us back online in 12 minutes. That kind of reliability matters in healthcare.",
    name: "Dr. Lisa Chang",
    role: "Practice Manager",
    company: "Evergreen Health",
    industry: "Healthcare",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  // Education
  {
    id: 33,
    quote:
      "Student engagement increased 40% after we adopted this platform. The interactive features make learning actually fun.",
    name: "Prof. David Miller",
    role: "Department Chair",
    company: "Westfield University",
    industry: "Education",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 34,
    quote:
      "This course completely changed my career trajectory. Within 3 months of completing it, I landed a job paying 60% more than my previous role.",
    name: "Ashley Rogers",
    role: "Student",
    company: "CodeAcademy Pro",
    industry: "Education",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 35,
    quote:
      "As an educator with 20 years of experience, I can say this is the best LMS I've ever used. The grading automation alone saves me 10 hours per week. The analytics dashboard shows me exactly where each student is struggling, so I can intervene early.",
    name: "Prof. Sarah Williams",
    role: "Professor",
    company: "Brighton College",
    industry: "Education",
    category: "Time Savings",
    length: "long",
    stars: 5,
  },
  {
    id: 36,
    quote:
      "Parent communication used to be our weakest area. Now we get compliments on it. The automated updates keep families informed without adding work for teachers.",
    name: "Mark Thompson",
    role: "Principal",
    company: "Oakdale Academy",
    industry: "Education",
    category: "Team Collaboration",
    length: "medium",
    stars: 5,
  },
  {
    id: 37,
    quote:
      "The content library is incredible. Thousands of ready-to-use lessons aligned with standards. It halved our prep time.",
    name: "Jessica Palmer",
    role: "Curriculum Director",
    company: "Horizon Schools",
    industry: "Education",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 38,
    quote:
      "Affordable for schools on tight budgets. The free tier alone covers most of what small schools need.",
    name: "Robert Garcia",
    role: "Superintendent",
    company: "Valley School District",
    industry: "Education",
    category: "Value for Money",
    length: "short",
    stars: 4,
  },
  {
    id: 39,
    quote:
      "Remote learning was a nightmare until we found this. Stable video, breakout rooms, built-in quizzes. Our attendance actually went up.",
    name: "Angela Davis",
    role: "Teacher",
    company: "Lincoln Middle School",
    industry: "Education",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 40,
    quote:
      "The onboarding for new teachers is so smooth. Walkthrough videos for everything and a support team that responds in minutes, not days.",
    name: "Chris Wright",
    role: "IT Coordinator",
    company: "Riverside Academy",
    industry: "Education",
    category: "Onboarding",
    length: "medium",
    stars: 5,
  },
  // Financial Services
  {
    id: 41,
    quote:
      "Compliance reporting that used to take 3 days now takes 3 hours. Our auditors were impressed.",
    name: "Richard Hong",
    role: "Compliance Officer",
    company: "Sterling Capital",
    industry: "Financial Services",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 42,
    quote:
      "They helped us restructure our portfolio during the downturn. While others panicked, we were positioned for recovery. Returns exceeded benchmarks by 8%.",
    name: "Patricia Walsh",
    role: "Client",
    company: "Meridian Wealth",
    industry: "Financial Services",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 43,
    quote:
      "The client portal is beautiful and functional. Clients check their accounts themselves now instead of calling us. Support tickets dropped 60%.",
    name: "Daniel Brooks",
    role: "Managing Director",
    company: "Atlas Financial",
    industry: "Financial Services",
    category: "Ease of Use",
    length: "medium",
    stars: 5,
  },
  {
    id: 44,
    quote:
      "Security was our non-negotiable. SOC 2 Type II certified, bank-level encryption, and their security team meets with ours quarterly. No compromises.",
    name: "Victoria Chen",
    role: "CISO",
    company: "Pacific Trust",
    industry: "Financial Services",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 45,
    quote:
      "Loan processing time dropped from 5 days to 8 hours. Our customers are thrilled and our team isn't drowning in paperwork anymore.",
    name: "Thomas Green",
    role: "Branch Manager",
    company: "Community Credit Union",
    industry: "Financial Services",
    category: "Time Savings",
    length: "medium",
    stars: 5,
  },
  {
    id: 46,
    quote: "Straightforward pricing. No hidden fees. Exactly what you'd want from a financial partner.",
    name: "Susan Park",
    role: "CFO",
    company: "Beacon Advisors",
    industry: "Financial Services",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 47,
    quote:
      "Their team understood our regulatory requirements from day one. Implementation was smooth, and they handled the data migration flawlessly. We were live in 6 weeks — half the time our previous vendor quoted.",
    name: "Andrew Martinez",
    role: "COO",
    company: "Heritage Bank",
    industry: "Financial Services",
    category: "Onboarding",
    length: "long",
    stars: 5,
  },
  {
    id: 48,
    quote:
      "When we had a critical issue at 2 AM on a Saturday, their support team was on a call with us within 15 minutes. That's the kind of reliability you need in finance.",
    name: "Michelle Taylor",
    role: "Operations Manager",
    company: "Pinnacle Investments",
    industry: "Financial Services",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  // Real Estate
  {
    id: 49,
    quote:
      "Closed 40% more deals this year compared to last. The CRM automation handles follow-ups so nothing falls through the cracks.",
    name: "Brandon Lewis",
    role: "Broker",
    company: "Summit Realty",
    industry: "Real Estate",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 50,
    quote:
      "The virtual tour feature sells properties before buyers even visit. We've had multiple sight-unseen offers since implementing it.",
    name: "Nicole Foster",
    role: "Agent",
    company: "Coastal Properties",
    industry: "Real Estate",
    category: "Product Quality",
    length: "short",
    stars: 5,
  },
  {
    id: 51,
    quote:
      "They found us our dream home in a market where houses sell in 24 hours. Professional, responsive, and genuinely cared about finding the right fit — not just closing fast.",
    name: "David & Maria Johnson",
    role: "Homebuyers",
    company: "Bay Area",
    industry: "Real Estate",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  {
    id: 52,
    quote:
      "Marketing collateral used to take days to prepare. Now I generate professional listings in minutes with automated staging photos and neighborhood data.",
    name: "Samantha Reed",
    role: "Realtor",
    company: "Metro Homes",
    industry: "Real Estate",
    category: "Time Savings",
    length: "medium",
    stars: 5,
  },
  {
    id: 53,
    quote:
      "New agents on our team are productive in their first week. The training modules and mentorship matching make onboarding effortless.",
    name: "Robert Chen",
    role: "Team Lead",
    company: "Keystone Real Estate",
    industry: "Real Estate",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  {
    id: 54,
    quote:
      "The market analytics are a game-changer. I walk into listing appointments with data my competitors don't have. Sellers take me seriously.",
    name: "Tiffany Brown",
    role: "Senior Agent",
    company: "Premier Realty Group",
    industry: "Real Estate",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 55,
    quote: "Saved our brokerage $3,200/month by consolidating five tools into one.",
    name: "Greg Wilson",
    role: "Managing Broker",
    company: "Alliance Properties",
    industry: "Real Estate",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 56,
    quote:
      "Transaction management used to be chaos. Now every document, deadline, and communication is in one place. Our error rate went to nearly zero.",
    name: "Amanda Cross",
    role: "Transaction Coordinator",
    company: "Redwood Realty",
    industry: "Real Estate",
    category: "Ease of Use",
    length: "medium",
    stars: 5,
  },
  // Consulting
  {
    id: 57,
    quote:
      "They identified $2M in cost savings we completely overlooked. The engagement paid for itself 10x over.",
    name: "Robert Hayes",
    role: "CEO",
    company: "Apex Manufacturing",
    industry: "Consulting",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 58,
    quote:
      "Unlike other consultants, they didn't just hand us a report and leave. They stayed through implementation and made sure every recommendation actually worked in practice.",
    name: "Catherine Liu",
    role: "VP of Operations",
    company: "Velocity Corp",
    industry: "Consulting",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  {
    id: 59,
    quote:
      "Our team morale was at an all-time low. Six months after the organizational restructuring they guided us through, engagement scores hit a record high. They handled the human side with remarkable sensitivity.",
    name: "Mark Rodriguez",
    role: "CHRO",
    company: "Quantum Industries",
    industry: "Consulting",
    category: "ROI & Results",
    length: "long",
    stars: 5,
  },
  {
    id: 60,
    quote:
      "The proposal management system cut our response time from 2 weeks to 3 days. We're winning more contracts because we're first to respond.",
    name: "Laura Bennett",
    role: "BD Director",
    company: "Strategy First",
    industry: "Consulting",
    category: "Time Savings",
    length: "medium",
    stars: 5,
  },
  {
    id: 61,
    quote:
      "Clear methodologies, transparent pricing, no scope creep. They respect budgets, which is rare in consulting.",
    name: "Paul Anderson",
    role: "CFO",
    company: "Bridgewater Group",
    industry: "Consulting",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 62,
    quote:
      "Their junior consultants are more capable than senior people at other firms. The talent density is exceptional.",
    name: "Diana Wells",
    role: "Managing Partner",
    company: "Horizon Capital",
    industry: "Consulting",
    category: "Product Quality",
    length: "short",
    stars: 5,
  },
  {
    id: 63,
    quote:
      "Knowledge transfer was seamless. Our internal team felt confident running the new processes independently within weeks.",
    name: "Steve Kim",
    role: "Director of Strategy",
    company: "NovaTech",
    industry: "Consulting",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  {
    id: 64,
    quote:
      "The collaboration tools made working across time zones effortless. Shared dashboards, async updates, and clean documentation meant nothing got lost.",
    name: "Rachel Nguyen",
    role: "Project Manager",
    company: "CorePath Advisory",
    industry: "Consulting",
    category: "Team Collaboration",
    length: "medium",
    stars: 5,
  },
  // Fitness & Wellness
  {
    id: 65,
    quote:
      "Member retention went from 65% to 88% after implementing the automated check-in and progress tracking system.",
    name: "Jake Martinez",
    role: "Gym Owner",
    company: "IronWorks Fitness",
    industry: "Fitness & Wellness",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 66,
    quote:
      "Lost 30 pounds in 4 months. The personalized meal plans and weekly coaching calls kept me accountable in a way no app ever could.",
    name: "Melissa Grant",
    role: "Client",
    company: "FitLife Coaching",
    industry: "Fitness & Wellness",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 67,
    quote:
      "The booking system eliminated double-bookings and no-shows. Automated reminders mean my classes are consistently full. Revenue is up 25% with the same schedule.",
    name: "Taylor Brooks",
    role: "Studio Owner",
    company: "Zen Yoga Studio",
    industry: "Fitness & Wellness",
    category: "Time Savings",
    length: "medium",
    stars: 5,
  },
  {
    id: 68,
    quote:
      "As a personal trainer, this app lets me manage 40+ clients without feeling overwhelmed. Workout programming, progress photos, messaging — all in one place.",
    name: "Chris Davis",
    role: "Personal Trainer",
    company: "Peak Performance",
    industry: "Fitness & Wellness",
    category: "Ease of Use",
    length: "medium",
    stars: 5,
  },
  {
    id: 69,
    quote:
      "The virtual class platform is buttery smooth. No lag, great audio quality, and the on-demand library keeps members engaged between live sessions.",
    name: "Amanda Foster",
    role: "Instructor",
    company: "CoreFlow",
    industry: "Fitness & Wellness",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 70,
    quote: "Best value in the wellness tech space. We replaced three separate subscriptions.",
    name: "Ryan Park",
    role: "Operations Manager",
    company: "BodyBalance",
    industry: "Fitness & Wellness",
    category: "Value for Money",
    length: "short",
    stars: 4,
  },
  {
    id: 71,
    quote:
      "I've been to a lot of gyms. This is the first one where the staff actually remembers my name and goals. The community here is special.",
    name: "Sarah Mitchell",
    role: "Member",
    company: "CrossFit Harbor",
    industry: "Fitness & Wellness",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  {
    id: 72,
    quote:
      "Onboarding new trainers used to take 3 weeks. With the template library and SOPs built into the platform, we're down to 4 days.",
    name: "Monica Reyes",
    role: "Training Director",
    company: "FitHub",
    industry: "Fitness & Wellness",
    category: "Onboarding",
    length: "medium",
    stars: 5,
  },
  // Food & Restaurant
  {
    id: 73,
    quote:
      "Online orders increased 150% after launching the new ordering system. Kitchen tickets are clearer and errors dropped dramatically.",
    name: "Marco Rossi",
    role: "Owner",
    company: "Rossi's Trattoria",
    industry: "Food & Restaurant",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 74,
    quote:
      "The food was exceptional, but what really stood out was the service. Our server remembered our allergies from a previous visit months ago. That attention to detail is rare.",
    name: "Jennifer & Tom Clark",
    role: "Diners",
    company: "The Olive Branch",
    industry: "Food & Restaurant",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  {
    id: 75,
    quote:
      "Inventory waste dropped 40% in the first month. The predictive ordering feature is scary accurate — it knows what we'll need before we do.",
    name: "Angela Kim",
    role: "General Manager",
    company: "Fusion Kitchen",
    industry: "Food & Restaurant",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 76,
    quote:
      "Staff scheduling was a nightmare with 30 employees across shifts. Now it takes 10 minutes a week and everyone's happier with their schedules.",
    name: "Carlos Rivera",
    role: "Operations Manager",
    company: "Taco Loco",
    industry: "Food & Restaurant",
    category: "Time Savings",
    length: "medium",
    stars: 5,
  },
  {
    id: 77,
    quote: "Best catering experience we've ever had. On time, beautiful presentation, and the guests couldn't stop raving about the food.",
    name: "Sarah Foster",
    role: "Event Planner",
    company: "Events by Sarah",
    industry: "Food & Restaurant",
    category: "Product Quality",
    length: "short",
    stars: 5,
  },
  {
    id: 78,
    quote:
      "The POS system pays for itself. Faster checkout, integrated loyalty program, and the analytics show me exactly which menu items to push.",
    name: "David Chang",
    role: "Owner",
    company: "BowlHouse",
    industry: "Food & Restaurant",
    category: "Value for Money",
    length: "medium",
    stars: 5,
  },
  {
    id: 79,
    quote:
      "We trained the entire front-of-house team on the new system in one shift. That's unheard of for restaurant tech.",
    name: "Lisa O'Brien",
    role: "Training Manager",
    company: "Harbor Grill",
    industry: "Food & Restaurant",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  {
    id: 80,
    quote:
      "The reservation system with automated table management means we seat 20% more covers per night without anyone feeling rushed. That's real money.",
    name: "James Wilson",
    role: "Restaurant Director",
    company: "The Capital Room",
    industry: "Food & Restaurant",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  // Legal
  {
    id: 81,
    quote:
      "Document review time dropped 70% with the AI-assisted contract analysis. Our paralegals focus on substance, not formatting.",
    name: "Jennifer Walsh",
    role: "Partner",
    company: "Walsh & Associates",
    industry: "Legal",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 82,
    quote:
      "They handled our case with the professionalism and urgency it deserved. Settlement exceeded our expectations by 40%. I wish I'd found them sooner.",
    name: "Michael Torres",
    role: "Client",
    company: "Personal Injury Case",
    industry: "Legal",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 83,
    quote:
      "Billable hour tracking used to be our firm's biggest friction point. Automated time capture eliminated the end-of-month scramble and we're capturing 15% more billable time.",
    name: "Patricia Chen",
    role: "Managing Partner",
    company: "Chen Legal Group",
    industry: "Legal",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 84,
    quote:
      "Client communication is transformed. The secure portal means no more sensitive documents floating around in email. Clients love the transparency.",
    name: "Andrew Foster",
    role: "Attorney",
    company: "Foster Law",
    industry: "Legal",
    category: "Ease of Use",
    length: "medium",
    stars: 5,
  },
  {
    id: 85,
    quote:
      "As a solo practitioner, this practice management software lets me compete with firms 10x my size. Case management, billing, client intake — everything in one place.",
    name: "Rebecca Kim",
    role: "Solo Attorney",
    company: "Kim Law Office",
    industry: "Legal",
    category: "Value for Money",
    length: "medium",
    stars: 5,
  },
  {
    id: 86,
    quote:
      "Conflict checks that took hours now take seconds. Critical for a firm our size where missing a conflict could be catastrophic.",
    name: "David Stone",
    role: "Risk Manager",
    company: "Stone & Partners",
    industry: "Legal",
    category: "Time Savings",
    length: "short",
    stars: 5,
  },
  {
    id: 87,
    quote:
      "The e-discovery tools saved us $200,000 on a single case compared to what we would have spent outsourcing. Accuracy was actually better too.",
    name: "Lisa Hammond",
    role: "Litigation Partner",
    company: "Hammond & Gray",
    industry: "Legal",
    category: "ROI & Results",
    length: "medium",
    stars: 5,
  },
  {
    id: 88,
    quote:
      "New associates are up to speed in days instead of weeks. The template library and matter management system make the learning curve almost flat.",
    name: "James Bradford",
    role: "Senior Partner",
    company: "Bradford Legal",
    industry: "Legal",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  // Construction & Home
  {
    id: 89,
    quote:
      "Project timelines are now accurate to within 2 days. Clients trust our estimates and change orders dropped 60%.",
    name: "Mike Sullivan",
    role: "General Contractor",
    company: "Sullivan Construction",
    industry: "Construction & Home",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 90,
    quote:
      "They renovated our entire kitchen in 3 weeks — on budget and ahead of schedule. The design team listened to what we wanted and made it even better than we imagined.",
    name: "Karen & Steve Wilson",
    role: "Homeowners",
    company: "Kitchen Renovation",
    industry: "Construction & Home",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 91,
    quote:
      "Subcontractor management used to be chaos. The scheduling and communication tools mean everyone knows what they're doing and when. Rework is down 45%.",
    name: "Tony Garcia",
    role: "Project Manager",
    company: "BuildRight",
    industry: "Construction & Home",
    category: "Team Collaboration",
    length: "medium",
    stars: 5,
  },
  {
    id: 92,
    quote:
      "The estimating software paid for a year's subscription on the first job. Proposals look professional and the accuracy wins us bids.",
    name: "Dave Peterson",
    role: "Owner",
    company: "Peterson Homes",
    industry: "Construction & Home",
    category: "Value for Money",
    length: "short",
    stars: 5,
  },
  {
    id: 93,
    quote:
      "Safety compliance tracking across 12 active sites was impossible before. Now every inspection, certification, and incident is documented and accessible. OSHA audits are stress-free.",
    name: "Sandra Williams",
    role: "Safety Director",
    company: "CoreBuild Corp",
    industry: "Construction & Home",
    category: "Ease of Use",
    length: "long",
    stars: 5,
  },
  {
    id: 94,
    quote:
      "The photo documentation feature alone is worth it. Daily progress photos tagged to floor plans — clients love the transparency and it protects us from disputes.",
    name: "Rob Taylor",
    role: "Site Manager",
    company: "Landmark Builders",
    industry: "Construction & Home",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 95,
    quote:
      "They showed up when they said they would, finished when they said they would, and charged what they said they would. That's a unicorn in home renovation.",
    name: "Amy Brooks",
    role: "Homeowner",
    company: "Bathroom Remodel",
    industry: "Construction & Home",
    category: "Customer Support",
    length: "medium",
    stars: 5,
  },
  {
    id: 96,
    quote:
      "New crew members get up to speed with the mobile app training modules. No more shadowing for weeks — they're contributing on day two.",
    name: "Luis Ramirez",
    role: "Operations Director",
    company: "Ramirez & Sons",
    industry: "Construction & Home",
    category: "Onboarding",
    length: "short",
    stars: 5,
  },
  // Extra cross-industry examples
  {
    id: 97,
    quote: "If you're on the fence, just try it. I waited 6 months and wish I hadn't.",
    name: "Christina Moore",
    role: "Founder",
    company: "BrightPath",
    industry: "SaaS & Software",
    category: "Product Quality",
    length: "short",
    stars: 5,
  },
  {
    id: 98,
    quote:
      "The customer success team proactively reaches out with tips and optimizations. They care about our results, not just our subscription.",
    name: "Nathan Cole",
    role: "Director of Operations",
    company: "Apex Solutions",
    industry: "Consulting",
    category: "Customer Support",
    length: "short",
    stars: 5,
  },
  {
    id: 99,
    quote:
      "We went from 2 hours of daily manual data entry to zero. The integrations handle everything automatically. My team finally works on things that matter.",
    name: "Kelly Zhang",
    role: "Operations Manager",
    company: "Swift Logistics",
    industry: "E-commerce",
    category: "Time Savings",
    length: "medium",
    stars: 5,
  },
  {
    id: 100,
    quote:
      "Three years in and it keeps getting better. The product roadmap shows they listen to users. Every quarterly update has at least one feature we asked for.",
    name: "Brian Patterson",
    role: "CTO",
    company: "Vertex Tech",
    industry: "SaaS & Software",
    category: "Product Quality",
    length: "medium",
    stars: 5,
  },
  {
    id: 101,
    quote:
      "The ROI dashboard makes it easy to justify the investment to our board. Hard numbers, real impact, no guesswork.",
    name: "Helen Morris",
    role: "VP of Finance",
    company: "Cascade Group",
    industry: "Financial Services",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
  {
    id: 102,
    quote:
      "I recommend this to everyone I know. Not because they asked me to, but because it genuinely made my life easier.",
    name: "Derek Chang",
    role: "Small Business Owner",
    company: "Chang's Auto",
    industry: "Construction & Home",
    category: "Ease of Use",
    length: "short",
    stars: 5,
  },
  {
    id: 103,
    quote:
      "The free plan was generous enough that we could fully evaluate before committing. No bait-and-switch, no aggressive upselling. When we upgraded, it was because we wanted to, not because we had to.",
    name: "Olivia Peters",
    role: "Founder",
    company: "Bloom Studio",
    industry: "Marketing Agency",
    category: "Value for Money",
    length: "long",
    stars: 5,
  },
  {
    id: 104,
    quote:
      "My students' test scores improved an average of 18% after I started using the adaptive learning modules. The data doesn't lie.",
    name: "Prof. James Miller",
    role: "Professor",
    company: "State University",
    industry: "Education",
    category: "ROI & Results",
    length: "short",
    stars: 5,
  },
];
