export interface ReviewResponse {
  id: number;
  reviewType: "5-star" | "4-star" | "3-star" | "2-star" | "1-star";
  industry: string;
  tone: string;
  reviewText: string;
  responseText: string;
  stars: number;
}

export const reviewTypes = [
  "All Types",
  "Positive (5-star)",
  "Positive (4-star)",
  "Neutral (3-star)",
  "Negative (2-star)",
  "Negative (1-star)",
] as const;

export const industries = [
  "All Industries",
  "Restaurant",
  "Hotel",
  "Healthcare",
  "Retail",
  "SaaS",
  "Professional Services",
  "Home Services",
  "Fitness",
  "Salon/Spa",
  "Auto",
] as const;

export const tones = [
  "All Tones",
  "Professional",
  "Friendly",
  "Empathetic",
  "Apologetic",
] as const;

export const responses: ReviewResponse[] = [
  // ===== RESTAURANT =====
  // 5-star
  {
    id: 1,
    reviewType: "5-star",
    industry: "Restaurant",
    tone: "Friendly",
    reviewText: "Best pasta I've ever had! The service was amazing and the atmosphere was perfect for our anniversary dinner.",
    responseText: "Thank you so much for choosing us for your anniversary! We're thrilled the pasta and atmosphere made your evening special. Our chef takes great pride in our handmade pasta, and your kind words mean the world. We hope to welcome you back for many more celebrations!",
    stars: 5,
  },
  {
    id: 2,
    reviewType: "5-star",
    industry: "Restaurant",
    tone: "Professional",
    reviewText: "Outstanding brunch experience. Every dish was perfectly prepared and beautifully presented.",
    responseText: "Thank you for your wonderful review. We are delighted to hear that our brunch met your expectations in both quality and presentation. Our kitchen team works hard to ensure every plate leaves the kitchen at its best. We look forward to serving you again soon.",
    stars: 5,
  },
  {
    id: 3,
    reviewType: "4-star",
    industry: "Restaurant",
    tone: "Friendly",
    reviewText: "Really great food but the wait was a bit long on a Saturday night. Would still come back though!",
    responseText: "Thanks for the kind words about our food! We hear you on the Saturday wait times -- weekends are our busiest, but we're working on ways to improve the flow. Next time, feel free to make a reservation online to skip the wait. Can't wait to have you back!",
    stars: 4,
  },
  {
    id: 4,
    reviewType: "3-star",
    industry: "Restaurant",
    tone: "Empathetic",
    reviewText: "Food was decent but nothing special. Service was slow and we had to ask for water refills multiple times.",
    responseText: "Thank you for your honest feedback. We understand how frustrating slow service can be, especially when basic needs like water refills aren't met promptly. This isn't the standard we hold ourselves to, and we're addressing this with our team. We'd love a chance to show you the experience we're known for -- please reach out and your next visit is on us.",
    stars: 3,
  },
  {
    id: 5,
    reviewType: "2-star",
    industry: "Restaurant",
    tone: "Apologetic",
    reviewText: "Ordered the steak medium-rare and it came out well done. When we sent it back it took forever to get a replacement.",
    responseText: "We sincerely apologize for this experience. Getting a steak cooked incorrectly and then facing a long wait for the replacement is unacceptable. We've spoken with our kitchen team about this. We'd like to make this right -- please contact us directly so we can offer you a complimentary meal. Your satisfaction matters to us.",
    stars: 2,
  },
  {
    id: 6,
    reviewType: "1-star",
    industry: "Restaurant",
    tone: "Apologetic",
    reviewText: "Found a hair in my soup. Disgusting. Manager didn't seem to care when I complained.",
    responseText: "We are deeply sorry for this unacceptable experience. Finding a foreign object in food is something we take extremely seriously, and the response you received from management was not appropriate. We have implemented additional kitchen protocols and addressed this with our staff. Please contact us directly at your convenience -- we want to make this right and ensure this never happens again.",
    stars: 1,
  },
  {
    id: 7,
    reviewType: "5-star",
    industry: "Restaurant",
    tone: "Empathetic",
    reviewText: "We came in with food allergies and the staff went above and beyond to accommodate us. Finally a place that takes allergies seriously!",
    responseText: "This means so much to us! We know how stressful dining out can be when you have food allergies, and we believe everyone deserves a safe and enjoyable meal. Our team is trained to handle allergy accommodations with the utmost care. We're so glad you felt looked after, and we'd love to welcome you back anytime.",
    stars: 5,
  },
  {
    id: 8,
    reviewType: "1-star",
    industry: "Restaurant",
    tone: "Professional",
    reviewText: "Reservation wasn't honored. Waited 45 minutes even though we booked a week in advance.",
    responseText: "We sincerely apologize for not honoring your reservation. This falls short of our standards, and we understand your frustration after planning ahead. We are reviewing our reservation system to prevent this from happening again. Please reach out to us directly so we can make this right for you.",
    stars: 1,
  },

  // ===== HOTEL =====
  {
    id: 9,
    reviewType: "5-star",
    industry: "Hotel",
    tone: "Professional",
    reviewText: "Impeccable service from check-in to checkout. Room was spotless and the view was breathtaking.",
    responseText: "Thank you for your gracious review. We are pleased that our team delivered the level of service we strive for. The comfort and satisfaction of our guests is our top priority, and it is wonderful to know we exceeded your expectations. We look forward to welcoming you again on your next visit.",
    stars: 5,
  },
  {
    id: 10,
    reviewType: "5-star",
    industry: "Hotel",
    tone: "Friendly",
    reviewText: "The concierge recommended the most amazing local restaurant. Every detail of our stay was perfect!",
    responseText: "We're so happy you loved the restaurant recommendation! Our concierge team lives for moments like these -- helping guests discover hidden gems is one of our favorite things. Thrilled every detail was on point. Come back soon and we'll have more great suggestions ready for you!",
    stars: 5,
  },
  {
    id: 11,
    reviewType: "4-star",
    industry: "Hotel",
    tone: "Professional",
    reviewText: "Beautiful property and great location. Only thing missing was a gym that's open 24 hours.",
    responseText: "Thank you for your kind review. We appreciate the feedback regarding our gym hours. This is something we are actively evaluating to better serve our guests' schedules. We are glad you enjoyed the property and location, and we hope to welcome you back with an even better experience.",
    stars: 4,
  },
  {
    id: 12,
    reviewType: "3-star",
    industry: "Hotel",
    tone: "Empathetic",
    reviewText: "Room was nice but the walls are paper thin. Could hear everything from the room next door all night.",
    responseText: "We completely understand how disruptive noise can be when you're trying to rest. Thank you for bringing this to our attention. We take guest comfort seriously and are looking into soundproofing options. For your next stay, we'd be happy to arrange a room in a quieter section of the hotel. Please contact us directly and we'll take care of you.",
    stars: 3,
  },
  {
    id: 13,
    reviewType: "2-star",
    industry: "Hotel",
    tone: "Apologetic",
    reviewText: "Room wasn't ready at check-in time even though we arrived at 4 PM. No apology from the front desk.",
    responseText: "We sincerely apologize for the delayed room and the lack of acknowledgment from our front desk. You deserved a warm welcome and a room ready on time. We have addressed this with our housekeeping and front desk teams. We'd like to offer you an upgrade on your next stay -- please reach out to us directly.",
    stars: 2,
  },
  {
    id: 14,
    reviewType: "1-star",
    industry: "Hotel",
    tone: "Apologetic",
    reviewText: "Dirty bathroom, stained sheets, and broken AC. For this price? Absolutely not.",
    responseText: "We are deeply sorry for the condition of your room. This is completely unacceptable and does not reflect our standards. We have launched an immediate investigation and are conducting additional inspections. Please contact our guest services team directly -- we want to issue a full refund and ensure this is resolved. Thank you for bringing this to our attention.",
    stars: 1,
  },
  {
    id: 15,
    reviewType: "4-star",
    industry: "Hotel",
    tone: "Friendly",
    reviewText: "Love the rooftop pool! Staff was super welcoming. Just wish breakfast had more options.",
    responseText: "So glad you loved the rooftop pool -- it's one of our favorites too! Thanks for the note about breakfast. We're actually working on expanding the menu with more options this season. We'll make sure your next visit has even more to enjoy. See you soon!",
    stars: 4,
  },

  // ===== HEALTHCARE =====
  {
    id: 16,
    reviewType: "5-star",
    industry: "Healthcare",
    tone: "Professional",
    reviewText: "Dr. Smith was thorough, patient, and explained everything clearly. Best doctor visit I've had in years.",
    responseText: "Thank you for your kind words about Dr. Smith. We believe that clear communication and thorough care are essential to the patient experience. Your feedback has been shared with Dr. Smith and our entire team. We are honored to be part of your healthcare journey and look forward to your continued trust.",
    stars: 5,
  },
  {
    id: 17,
    reviewType: "5-star",
    industry: "Healthcare",
    tone: "Empathetic",
    reviewText: "The nursing staff was incredibly gentle and reassuring during my procedure. Made a scary experience much easier.",
    responseText: "We're so grateful you shared this. We understand that medical procedures can be anxiety-inducing, and our nursing team works hard to provide comfort and reassurance during those moments. Knowing they helped ease your experience is the highest compliment they could receive. We're here for you whenever you need us.",
    stars: 5,
  },
  {
    id: 18,
    reviewType: "4-star",
    industry: "Healthcare",
    tone: "Professional",
    reviewText: "Great doctors but the scheduling system is outdated. Hard to book appointments online.",
    responseText: "Thank you for your positive feedback about our medical team. We appreciate your candid input about our scheduling system. We are currently in the process of upgrading our online booking platform to make appointment scheduling more convenient. We expect the new system to be live soon and will share updates.",
    stars: 4,
  },
  {
    id: 19,
    reviewType: "3-star",
    industry: "Healthcare",
    tone: "Empathetic",
    reviewText: "Waited over an hour past my appointment time. The doctor was great once I got in but the wait was excessive.",
    responseText: "We understand how valuable your time is, and we sincerely apologize for the long wait. We know that extended wait times can add stress to an already important visit. We're reviewing our scheduling practices to reduce delays while still ensuring each patient receives the thorough attention they deserve. Thank you for your patience and feedback.",
    stars: 3,
  },
  {
    id: 20,
    reviewType: "2-star",
    industry: "Healthcare",
    tone: "Apologetic",
    reviewText: "Billing department is a nightmare. Got charged for services that were supposed to be covered by insurance.",
    responseText: "We sincerely apologize for the billing confusion. We understand how frustrating incorrect charges can be, and this is not the experience we want for our patients. Please contact our billing department directly at your earliest convenience so we can review your account, correct any errors, and ensure your insurance coverage is properly applied.",
    stars: 2,
  },
  {
    id: 21,
    reviewType: "1-star",
    industry: "Healthcare",
    tone: "Professional",
    reviewText: "Front desk staff was rude and dismissive. Made me feel like an inconvenience for asking a simple question.",
    responseText: "We are very sorry to hear about your experience with our front desk staff. Every patient deserves to be treated with courtesy and respect, and we have addressed this matter directly with our team. We would appreciate the opportunity to discuss this further -- please contact our office manager so we can ensure this does not happen again.",
    stars: 1,
  },
  {
    id: 22,
    reviewType: "3-star",
    industry: "Healthcare",
    tone: "Professional",
    reviewText: "Clinic is clean and modern but felt rushed during my appointment. Didn't get all my questions answered.",
    responseText: "Thank you for your feedback. We are glad you found our facility well-maintained. However, we are sorry you felt rushed during your visit. Every patient deserves adequate time to have their questions addressed. We are reviewing our appointment scheduling to ensure we allocate sufficient time for each patient. Please do not hesitate to call us with any remaining questions.",
    stars: 3,
  },

  // ===== RETAIL =====
  {
    id: 23,
    reviewType: "5-star",
    industry: "Retail",
    tone: "Friendly",
    reviewText: "Found exactly what I was looking for! Staff was helpful without being pushy. Will definitely be back.",
    responseText: "Yay, that's what we love to hear! Our team is trained to be there when you need them and give you space when you don't. So glad they helped you find the perfect item. We'll be here whenever you're ready for your next visit!",
    stars: 5,
  },
  {
    id: 24,
    reviewType: "5-star",
    industry: "Retail",
    tone: "Professional",
    reviewText: "Excellent product selection and competitive prices. The return policy is very customer-friendly too.",
    responseText: "Thank you for your review. We work hard to curate a selection that meets our customers' needs at fair prices. Our flexible return policy is part of our commitment to your complete satisfaction. We appreciate your business and look forward to serving you again.",
    stars: 5,
  },
  {
    id: 25,
    reviewType: "4-star",
    industry: "Retail",
    tone: "Friendly",
    reviewText: "Great store with good variety. Would love to see more sustainable product options though.",
    responseText: "Thanks for shopping with us and for the thoughtful suggestion! We're actually in the process of expanding our sustainable product line -- great minds think alike. Keep an eye out for new eco-friendly options arriving soon. Thanks for caring about sustainability as much as we do!",
    stars: 4,
  },
  {
    id: 26,
    reviewType: "3-star",
    industry: "Retail",
    tone: "Professional",
    reviewText: "Online order arrived a day late. Product was fine but shipping needs improvement.",
    responseText: "Thank you for your feedback. We apologize for the shipping delay and understand how important timely delivery is. We are working with our logistics partners to improve fulfillment speed. We are glad the product met your expectations and will work to ensure a smoother delivery experience in the future.",
    stars: 3,
  },
  {
    id: 27,
    reviewType: "2-star",
    industry: "Retail",
    tone: "Apologetic",
    reviewText: "Received the wrong size and it took two weeks to get the exchange processed. Very frustrating.",
    responseText: "We sincerely apologize for sending the wrong size and for the lengthy exchange process. This is not the level of service we aim to provide. We have reviewed our fulfillment process and are making changes to prevent shipping errors. We'd like to offer you free expedited shipping on your next order -- please contact our support team.",
    stars: 2,
  },
  {
    id: 28,
    reviewType: "1-star",
    industry: "Retail",
    tone: "Apologetic",
    reviewText: "Product broke after one use. Customer service wouldn't process a refund because I didn't have the receipt.",
    responseText: "We are deeply sorry for the product failure and the difficulty you experienced with our return process. Product quality is something we stand behind, receipt or not. We are updating our return policy to better handle situations like this. Please contact our customer service manager directly -- we want to resolve this for you immediately.",
    stars: 1,
  },
  {
    id: 29,
    reviewType: "4-star",
    industry: "Retail",
    tone: "Empathetic",
    reviewText: "Love the loyalty program! Only reason it's not 5 stars is the parking situation is terrible on weekends.",
    responseText: "We're glad you're enjoying the loyalty program! We completely understand the frustration with weekend parking -- it's something we hear about and are actively working to address. In the meantime, we'd suggest visiting before noon on weekends when parking is usually easier. Thank you for being a loyal customer!",
    stars: 4,
  },

  // ===== SAAS =====
  {
    id: 30,
    reviewType: "5-star",
    industry: "SaaS",
    tone: "Professional",
    reviewText: "Incredible platform. Reduced our reporting time by 75%. The automation features are game-changing.",
    responseText: "Thank you for your excellent review. We are thrilled to hear about the significant time savings you've experienced with our automation features. Helping teams work more efficiently is at the core of our mission. We look forward to continuing to deliver value as we roll out even more features this year.",
    stars: 5,
  },
  {
    id: 31,
    reviewType: "5-star",
    industry: "SaaS",
    tone: "Friendly",
    reviewText: "Best customer support I've ever experienced with a software product. They actually care about their users!",
    responseText: "This makes our day! We genuinely love helping our users succeed, and it's amazing to know that comes through. Our support team will be thrilled to see this. We're always here when you need us -- don't hesitate to reach out!",
    stars: 5,
  },
  {
    id: 32,
    reviewType: "4-star",
    industry: "SaaS",
    tone: "Professional",
    reviewText: "Powerful tool with a steep learning curve. Once you get past the initial setup, it's fantastic.",
    responseText: "Thank you for your thoughtful review. We recognize that the initial setup can be complex, and we are actively working to simplify our onboarding experience. In the meantime, our learning center and dedicated onboarding specialists are available to help new users get up to speed quickly. We appreciate your patience and are glad it's paying off.",
    stars: 4,
  },
  {
    id: 33,
    reviewType: "3-star",
    industry: "SaaS",
    tone: "Empathetic",
    reviewText: "The product is good but pricing jumped significantly at renewal. Felt like a bait and switch.",
    responseText: "We hear you, and we understand how unexpected price changes can feel frustrating. Transparency is important to us, and we're sorry if the pricing adjustment wasn't communicated clearly. We'd like to review your account personally and explore options that work better for your budget. Please reach out to your account manager, and we'll find a solution together.",
    stars: 3,
  },
  {
    id: 34,
    reviewType: "2-star",
    industry: "SaaS",
    tone: "Apologetic",
    reviewText: "Platform went down for 6 hours during our busiest day of the year. No communication from the team.",
    responseText: "We sincerely apologize for the outage and the lack of communication during the incident. We understand how critical uptime is for your business, especially during peak periods. We have implemented new monitoring systems and a communication protocol to ensure timely updates during any future incidents. We'd like to discuss how we can make this right -- please contact your account manager.",
    stars: 2,
  },
  {
    id: 35,
    reviewType: "1-star",
    industry: "SaaS",
    tone: "Professional",
    reviewText: "Data export feature doesn't work properly. Lost hours of work trying to get our reports out.",
    responseText: "We apologize for the issues with our data export feature. This is a critical functionality that we take very seriously. Our engineering team has been notified and is working on a fix. In the meantime, please contact our support team for a workaround that can help you export your reports immediately. We will follow up with you once the fix is deployed.",
    stars: 1,
  },
  {
    id: 36,
    reviewType: "4-star",
    industry: "SaaS",
    tone: "Friendly",
    reviewText: "Love the new dashboard redesign! So much cleaner. Would be perfect if the mobile app got the same treatment.",
    responseText: "So glad you're loving the new dashboard! Our design team put a lot of thought into making it cleaner and more intuitive. Great news -- the mobile app redesign is already in the works and we think you're going to love it just as much. Stay tuned for updates!",
    stars: 4,
  },

  // ===== PROFESSIONAL SERVICES =====
  {
    id: 37,
    reviewType: "5-star",
    industry: "Professional Services",
    tone: "Professional",
    reviewText: "They handled our tax situation with expertise and saved us thousands. Highly recommend.",
    responseText: "Thank you for entrusting us with your tax planning. We are pleased to have been able to identify savings opportunities for you. Our team's goal is always to provide expert guidance that delivers tangible results. We appreciate your recommendation and look forward to continuing to serve you.",
    stars: 5,
  },
  {
    id: 38,
    reviewType: "5-star",
    industry: "Professional Services",
    tone: "Friendly",
    reviewText: "Made the whole legal process so much less stressful. They explained everything in plain English!",
    responseText: "That's exactly what we aim for! Legal matters can be intimidating, and we believe everyone deserves clear, jargon-free explanations. So happy we could take some of the stress off your plate. We're always here when you need us!",
    stars: 5,
  },
  {
    id: 39,
    reviewType: "4-star",
    industry: "Professional Services",
    tone: "Professional",
    reviewText: "Great accounting firm. Responsive and knowledgeable. Only wish their portal was more modern.",
    responseText: "Thank you for your review. We are glad our responsiveness and expertise have met your expectations. We appreciate the feedback regarding our client portal and are pleased to share that a modernized version is currently in development. We value your input as it helps us improve our services.",
    stars: 4,
  },
  {
    id: 40,
    reviewType: "3-star",
    industry: "Professional Services",
    tone: "Empathetic",
    reviewText: "Good work but communication could be better. I often had to follow up to get status updates.",
    responseText: "Thank you for your feedback. We understand how important consistent communication is, especially when you've entrusted important matters to our care. You shouldn't have to chase us for updates. We're implementing a new client communication system with regular status updates to ensure you always know where things stand. We appreciate your patience and candor.",
    stars: 3,
  },
  {
    id: 41,
    reviewType: "2-star",
    industry: "Professional Services",
    tone: "Apologetic",
    reviewText: "Missed a filing deadline that cost us penalty fees. Unacceptable for a professional firm.",
    responseText: "We sincerely apologize for this serious error. Missing a deadline is unacceptable, and we take full responsibility. We have reviewed our internal processes and implemented additional checks to prevent this from occurring again. We would like to cover the penalty fees and discuss this further -- please contact our managing partner directly.",
    stars: 2,
  },
  {
    id: 42,
    reviewType: "1-star",
    industry: "Professional Services",
    tone: "Professional",
    reviewText: "Overcharged for basic services and couldn't explain the invoice when I asked.",
    responseText: "We apologize for the billing concerns. Transparency in our pricing is fundamental to our practice, and we are sorry this was not your experience. We would like to review your invoice in detail and correct any discrepancies. Please contact our billing department at your earliest convenience so we can resolve this promptly.",
    stars: 1,
  },

  // ===== HOME SERVICES =====
  {
    id: 43,
    reviewType: "5-star",
    industry: "Home Services",
    tone: "Friendly",
    reviewText: "Plumber arrived on time, fixed the leak quickly, and cleaned up after himself. Rare to find such professionalism!",
    responseText: "Thank you for the awesome review! We believe showing up on time and leaving your home clean is the bare minimum -- glad to hear we hit the mark. We'll pass your kind words to our technician. Don't hesitate to call us next time you need anything around the house!",
    stars: 5,
  },
  {
    id: 44,
    reviewType: "5-star",
    industry: "Home Services",
    tone: "Professional",
    reviewText: "Complete kitchen remodel done on time and under budget. The craftsmanship is outstanding.",
    responseText: "Thank you for your generous review. We take great pride in delivering projects on time and within budget while maintaining the highest standards of craftsmanship. It was a pleasure working on your kitchen remodel. We stand behind our work and are here for any future projects you may have.",
    stars: 5,
  },
  {
    id: 45,
    reviewType: "4-star",
    industry: "Home Services",
    tone: "Friendly",
    reviewText: "Great landscaping work. Only small issue was the crew showed up later than the scheduled time.",
    responseText: "Thanks for the great feedback on the landscaping! We apologize for running behind -- sometimes jobs run a bit over, but we're working on better scheduling to minimize any delays. Your yard looks amazing and we loved working on it. We'll be more punctual next time, promise!",
    stars: 4,
  },
  {
    id: 46,
    reviewType: "3-star",
    industry: "Home Services",
    tone: "Empathetic",
    reviewText: "The painting looks good but they got paint on my hardwood floors. Had to spend extra time cleaning up.",
    responseText: "We understand how frustrating it must be to deal with cleanup after what should have been a finished job. Getting paint on your hardwood floors is not acceptable, and we're sorry this happened. We'd like to send our team back to properly clean and restore any affected areas at no charge. Please contact us to schedule this -- your satisfaction matters to us.",
    stars: 3,
  },
  {
    id: 47,
    reviewType: "2-star",
    industry: "Home Services",
    tone: "Apologetic",
    reviewText: "Electrician left without finishing the job and didn't come back for a week despite multiple calls.",
    responseText: "We sincerely apologize for the incomplete work and the poor follow-up. This is not how we operate, and we understand your frustration. We have addressed this with the technician and our dispatch team. We would like to send a senior electrician to complete the work immediately and compensate you for the inconvenience. Please contact our office directly.",
    stars: 2,
  },
  {
    id: 48,
    reviewType: "1-star",
    industry: "Home Services",
    tone: "Apologetic",
    reviewText: "HVAC system broke down again two days after they 'fixed' it. $500 wasted on a repair that didn't work.",
    responseText: "We are deeply sorry that the repair did not resolve your issue. We understand how frustrating and costly this situation is. We want to make this right immediately -- we will send our most experienced HVAC technician to diagnose and fix the issue at no additional charge. We also want to discuss reimbursing you for the initial repair. Please call us right away.",
    stars: 1,
  },
  {
    id: 49,
    reviewType: "4-star",
    industry: "Home Services",
    tone: "Professional",
    reviewText: "Reliable roofing company. Did a solid job on our roof replacement. Communication was excellent throughout.",
    responseText: "Thank you for your review. We are pleased to hear that our communication and workmanship met your expectations during the roof replacement. Keeping homeowners informed throughout the process is a priority for us. We appreciate your trust and are here for any future maintenance needs.",
    stars: 4,
  },

  // ===== FITNESS =====
  {
    id: 50,
    reviewType: "5-star",
    industry: "Fitness",
    tone: "Friendly",
    reviewText: "Best gym in town! Clean equipment, great classes, and the trainers actually remember your name.",
    responseText: "You just made our whole team smile! We're big believers that a gym should feel like a community, not just a building with weights. So glad our trainers make you feel at home. Keep crushing those workouts -- we're cheering you on!",
    stars: 5,
  },
  {
    id: 51,
    reviewType: "5-star",
    industry: "Fitness",
    tone: "Empathetic",
    reviewText: "I was nervous to start as a complete beginner but the staff made me feel so welcome. Down 30 pounds!",
    responseText: "We know how much courage it takes to walk through the gym doors for the first time, and we're SO proud of your 30-pound transformation! Your dedication is inspiring. Our team is here to support you every step of the way, and we can't wait to celebrate your next milestone with you!",
    stars: 5,
  },
  {
    id: 52,
    reviewType: "4-star",
    industry: "Fitness",
    tone: "Professional",
    reviewText: "Solid gym with good equipment selection. Could use a few more squat racks during peak hours.",
    responseText: "Thank you for your review. We appreciate the feedback about squat rack availability during peak times. We are evaluating our equipment layout and have plans to add additional power racks in Q2. We are committed to ensuring our members have access to the equipment they need.",
    stars: 4,
  },
  {
    id: 53,
    reviewType: "3-star",
    industry: "Fitness",
    tone: "Empathetic",
    reviewText: "Classes are great but the locker room could really use some attention. Showers aren't always clean.",
    responseText: "Thank you for your honest feedback. We understand that a clean locker room is essential to your gym experience, and we're sorry we've fallen short in that area. We've increased our cleaning schedule and are conducting more frequent inspections throughout the day. Clean facilities are non-negotiable for us, and we appreciate you bringing this to our attention.",
    stars: 3,
  },
  {
    id: 54,
    reviewType: "2-star",
    industry: "Fitness",
    tone: "Apologetic",
    reviewText: "Signed up for personal training but my trainer cancelled three sessions in a row with last-minute notice.",
    responseText: "We sincerely apologize for the repeated cancellations. When you invest in personal training, you deserve consistency and reliability. This is not the standard we uphold, and we've addressed this directly. We'd like to offer you three complimentary sessions with a new trainer and ensure your schedule is prioritized. Please contact our front desk to arrange this.",
    stars: 2,
  },
  {
    id: 55,
    reviewType: "1-star",
    industry: "Fitness",
    tone: "Professional",
    reviewText: "Impossible to cancel membership. Kept charging me for months after I submitted the cancellation form.",
    responseText: "We apologize for the difficulties with your membership cancellation. This is not an acceptable experience, and we are reviewing our cancellation process to ensure it is straightforward and properly honored. We will process your cancellation immediately and refund any charges incurred after your original cancellation request. Please contact our membership team so we can resolve this right away.",
    stars: 1,
  },

  // ===== SALON/SPA =====
  {
    id: 56,
    reviewType: "5-star",
    industry: "Salon/Spa",
    tone: "Friendly",
    reviewText: "Best haircut I've ever gotten! Maria really listened to what I wanted and nailed it.",
    responseText: "Maria is going to be SO happy to hear this! She's amazing at really listening and translating what clients envision into reality. We're thrilled you love your new look. Can't wait to see you at your next appointment!",
    stars: 5,
  },
  {
    id: 57,
    reviewType: "5-star",
    industry: "Salon/Spa",
    tone: "Professional",
    reviewText: "Exceptional spa experience. The deep tissue massage was exactly what I needed. Very relaxing atmosphere.",
    responseText: "Thank you for your kind review. We are delighted that your massage provided the relief you were seeking. Our therapists are dedicated to creating a restorative experience tailored to each client's needs. We look forward to welcoming you back for your next session.",
    stars: 5,
  },
  {
    id: 58,
    reviewType: "4-star",
    industry: "Salon/Spa",
    tone: "Friendly",
    reviewText: "Love the new renovation! Gorgeous space. Just wish they offered online booking.",
    responseText: "Thank you! We put a lot of love into the renovation and we're glad it shows. Great news -- we're launching online booking next month! You'll be able to book your appointments anytime, anywhere. Stay tuned for the announcement!",
    stars: 4,
  },
  {
    id: 59,
    reviewType: "3-star",
    industry: "Salon/Spa",
    tone: "Empathetic",
    reviewText: "Facial was nice but the aesthetician kept trying to upsell products the entire time. Took away from the relaxation.",
    responseText: "We completely understand how that could detract from the relaxing experience you came for. Spa time should be about your comfort and wellness, not sales pitches. We've spoken with our team about being mindful of this. We'd love to offer you a complimentary add-on on your next visit to make up for it.",
    stars: 3,
  },
  {
    id: 60,
    reviewType: "2-star",
    industry: "Salon/Spa",
    tone: "Apologetic",
    reviewText: "Hair color came out completely different from what I asked for. Had to go somewhere else to fix it.",
    responseText: "We are truly sorry that your color didn't turn out as expected. Having to visit another salon to fix it is not the experience you should have had. We take color accuracy seriously and would have liked the chance to correct it ourselves. We'd like to offer a complimentary color correction and consultation. Please reach out to us so we can make this right.",
    stars: 2,
  },
  {
    id: 61,
    reviewType: "1-star",
    industry: "Salon/Spa",
    tone: "Apologetic",
    reviewText: "Chemical burn from a treatment. Staff panicked instead of helping. Went to urgent care.",
    responseText: "We are deeply concerned and sorry to hear about this. Your safety and well-being are our absolute top priority, and this incident is being taken extremely seriously. We are conducting a thorough review of our protocols and the products involved. Please contact our manager directly so we can ensure you receive proper care and compensation. We sincerely apologize.",
    stars: 1,
  },

  // ===== AUTO =====
  {
    id: 62,
    reviewType: "5-star",
    industry: "Auto",
    tone: "Professional",
    reviewText: "Honest mechanics who don't try to upsell unnecessary repairs. Fixed the issue for half what the dealer quoted.",
    responseText: "Thank you for your review. Transparency and honest pricing are the foundation of our business. We believe in fixing what needs fixing and nothing more. We are glad we could provide a fair solution for you and appreciate your trust in our team. We look forward to keeping your vehicle in top condition.",
    stars: 5,
  },
  {
    id: 63,
    reviewType: "5-star",
    industry: "Auto",
    tone: "Friendly",
    reviewText: "These guys are the best! Got my car in and out in two hours and even washed it. Five stars all day!",
    responseText: "That's what we like to hear! Quick service with a little extra something -- the car wash is on us because we think you should drive away happy in every way. Thanks for the five-star love, and we'll see you at your next service!",
    stars: 5,
  },
  {
    id: 64,
    reviewType: "4-star",
    industry: "Auto",
    tone: "Professional",
    reviewText: "Good quality work and fair prices. Could improve the waiting area though -- it's pretty bare.",
    responseText: "Thank you for your feedback. We are glad the quality and pricing met your expectations. We appreciate the suggestion regarding our waiting area and are planning improvements including comfortable seating, Wi-Fi, and a refreshment station. We want the entire experience to be comfortable from start to finish.",
    stars: 4,
  },
  {
    id: 65,
    reviewType: "3-star",
    industry: "Auto",
    tone: "Empathetic",
    reviewText: "Repair took three days when they said it would be done in one. No loaner car offered.",
    responseText: "We understand how disruptive it is to be without your vehicle for longer than expected. We apologize for the delay and for not offering alternative transportation. We're updating our parts inventory system to reduce wait times and implementing a loaner car program for extended repairs. Your feedback is helping us improve.",
    stars: 3,
  },
  {
    id: 66,
    reviewType: "2-star",
    industry: "Auto",
    tone: "Apologetic",
    reviewText: "Oil change was fine but they left greasy fingerprints all over my steering wheel and dash. Come on.",
    responseText: "We sincerely apologize for leaving your vehicle in that condition. There is no excuse for returning a car dirtier than when it arrived. We have reinforced our quality inspection process and now use protective coverings during all services. We'd like to offer you a complimentary interior detail to make up for this. Please give us a call.",
    stars: 2,
  },
  {
    id: 67,
    reviewType: "1-star",
    industry: "Auto",
    tone: "Apologetic",
    reviewText: "Charged me for new brake pads that were clearly used. This is fraud.",
    responseText: "This is a very serious allegation that we want to investigate immediately. We stand behind the integrity of our work and use only new, quality parts. If there has been any error, we will correct it immediately and take appropriate action. Please contact our service manager directly so we can inspect the parts and review the documentation. We take this extremely seriously.",
    stars: 1,
  },
  {
    id: 68,
    reviewType: "4-star",
    industry: "Auto",
    tone: "Friendly",
    reviewText: "Great tire service and they found a potential issue with my alignment before it became a bigger problem.",
    responseText: "That's our team looking out for you! Catching potential issues early is what we do best -- it saves you money and keeps you safe on the road. Thanks for trusting us with your tires, and we're glad we could prevent a bigger headache down the line. See you next time!",
    stars: 4,
  },

  // ===== MORE RESTAURANT =====
  {
    id: 69,
    reviewType: "5-star",
    industry: "Restaurant",
    tone: "Professional",
    reviewText: "The tasting menu was an absolute culinary journey. Every course was a revelation.",
    responseText: "Thank you for such a wonderful compliment. Our chef curates the tasting menu to take guests on a journey through seasonal flavors and creative techniques. We are honored that you appreciated the experience and look forward to surprising your palate again on your next visit.",
    stars: 5,
  },
  {
    id: 70,
    reviewType: "2-star",
    industry: "Restaurant",
    tone: "Empathetic",
    reviewText: "Kids menu is terrible. Only fried food options. Not great for families trying to eat healthy.",
    responseText: "You raise a really valid point. Families should have nutritious options for their children, not just the typical fried fare. We're working with our chef to revamp the kids menu with healthier, kid-friendly choices. We appreciate you taking the time to share this -- it helps us become a better restaurant for all our guests.",
    stars: 2,
  },

  // ===== MORE HOTEL =====
  {
    id: 71,
    reviewType: "3-star",
    industry: "Hotel",
    tone: "Professional",
    reviewText: "Location is perfect but the Wi-Fi was painfully slow. Not ideal for a business trip.",
    responseText: "Thank you for your feedback. We understand that reliable, high-speed internet is essential for business travelers. We are currently upgrading our Wi-Fi infrastructure across the property to provide faster, more consistent connectivity. We anticipate the upgrade will be complete within the coming weeks and appreciate your patience.",
    stars: 3,
  },
  {
    id: 72,
    reviewType: "2-star",
    industry: "Hotel",
    tone: "Empathetic",
    reviewText: "Booked a 'deluxe' room that looked nothing like the photos online. Very misleading.",
    responseText: "We understand how disappointing it must be to arrive at a room that doesn't match your expectations from the photos. We are currently updating all our room photography to accurately represent each room type. We'd like to offer you a stay upgrade on your next visit to show you the experience we truly offer. Please contact us directly to arrange this.",
    stars: 2,
  },

  // ===== MORE HEALTHCARE =====
  {
    id: 73,
    reviewType: "4-star",
    industry: "Healthcare",
    tone: "Friendly",
    reviewText: "Love the new telehealth option! So convenient. Only wish it was available for all appointment types.",
    responseText: "We're so glad you're enjoying telehealth! It's been a game-changer for many of our patients. We're working on expanding the types of appointments available virtually -- it's definitely on our roadmap. Thanks for being an early adopter and for the great feedback!",
    stars: 4,
  },

  // ===== MORE RETAIL =====
  {
    id: 74,
    reviewType: "3-star",
    industry: "Retail",
    tone: "Friendly",
    reviewText: "Nice store layout but the checkout line was ridiculously long. Need more registers open.",
    responseText: "Thanks for the feedback! We know long checkout lines are no fun, and we hear you. We're adding self-checkout stations and scheduling more cashiers during busy hours. Appreciate your patience, and next time should be a much smoother experience!",
    stars: 3,
  },
  {
    id: 75,
    reviewType: "1-star",
    industry: "Retail",
    tone: "Empathetic",
    reviewText: "Website said item was in stock. Drove 30 minutes to the store and they didn't have it.",
    responseText: "We completely understand your frustration -- driving a long distance only to find the item unavailable is incredibly disappointing. We're improving our real-time inventory system to prevent these discrepancies. We'd like to ship the item to your home at no charge. Please contact us with the product details and we'll make it happen.",
    stars: 1,
  },

  // ===== MORE SAAS =====
  {
    id: 76,
    reviewType: "3-star",
    industry: "SaaS",
    tone: "Professional",
    reviewText: "Good functionality but the documentation is outdated and often inaccurate. Hard to self-serve.",
    responseText: "Thank you for this valuable feedback. We recognize that comprehensive, up-to-date documentation is essential for our users to get the most out of our platform. We have dedicated resources to a complete documentation overhaul that is currently underway. We appreciate your patience and welcome any specific areas you'd like us to prioritize.",
    stars: 3,
  },

  // ===== MORE PROFESSIONAL SERVICES =====
  {
    id: 77,
    reviewType: "5-star",
    industry: "Professional Services",
    tone: "Empathetic",
    reviewText: "Going through a difficult divorce and they handled everything with such compassion and discretion.",
    responseText: "Thank you for trusting us during such a difficult time. We understand how emotionally challenging this process is, and we are honored that you felt supported throughout. Our team is committed to handling sensitive matters with the compassion and discretion they deserve. We wish you all the best moving forward and are here if you need anything.",
    stars: 5,
  },

  // ===== MORE HOME SERVICES =====
  {
    id: 78,
    reviewType: "3-star",
    industry: "Home Services",
    tone: "Professional",
    reviewText: "Gutter cleaning was done well but the crew damaged some plants around the house. No mention of it.",
    responseText: "Thank you for bringing this to our attention. We apologize for the damage to your plants and for not informing you. Our crews are expected to treat your property with care and report any issues immediately. We will send a landscaping team to assess and restore the affected areas at our expense. Please contact us to schedule this.",
    stars: 3,
  },

  // ===== MORE FITNESS =====
  {
    id: 79,
    reviewType: "4-star",
    industry: "Fitness",
    tone: "Empathetic",
    reviewText: "Great variety of classes. I just wish there were more early morning options for those of us who work 9-5.",
    responseText: "We hear you! Early morning workouts before a full day of work takes real dedication, and we want to support that. We're looking at adding more 6 AM and 6:30 AM class options based on feedback like yours. Keep an eye on our schedule -- changes are coming, and we think you'll be happy!",
    stars: 4,
  },

  // ===== MORE SALON/SPA =====
  {
    id: 80,
    reviewType: "4-star",
    industry: "Salon/Spa",
    tone: "Professional",
    reviewText: "Consistently excellent manicures. The gel polish lasts three full weeks every time.",
    responseText: "Thank you for your loyal patronage and kind review. We are pleased that our gel manicures consistently meet your standards for longevity. Our nail technicians use only premium products and techniques to ensure lasting results. We look forward to your next appointment.",
    stars: 4,
  },
  {
    id: 81,
    reviewType: "3-star",
    industry: "Salon/Spa",
    tone: "Friendly",
    reviewText: "Massage was good but the room was a bit cold. Also, the music was too loud for a relaxation treatment.",
    responseText: "Thanks for the feedback! Temperature and ambiance are everything for a great spa experience, and we're sorry we missed the mark. We're adding individual room temperature controls and adjustable sound settings so each client can customize their environment. Next time will be much more zen -- we promise!",
    stars: 3,
  },

  // ===== MORE AUTO =====
  {
    id: 82,
    reviewType: "3-star",
    industry: "Auto",
    tone: "Professional",
    reviewText: "Service was fine but they didn't reset my service light. Small detail that matters.",
    responseText: "Thank you for your feedback. You are correct -- resetting the service light is a standard part of our post-service checklist, and we apologize for the oversight. We have reminded our technicians of the importance of completing every step in our quality protocol. Please feel free to stop by at your convenience and we will reset it immediately.",
    stars: 3,
  },
  {
    id: 83,
    reviewType: "5-star",
    industry: "Auto",
    tone: "Empathetic",
    reviewText: "My car broke down on the highway and they fit me in same-day even though they were fully booked. Lifesavers!",
    responseText: "We're so glad we could help when you needed it most! Being stranded on the highway is stressful and even scary. Our team always tries to make room for emergencies because we know how much you depend on your vehicle. We're happy your car is back in action, and we're always here if you need us!",
    stars: 5,
  },

  // ===== ADDITIONAL RESPONSES FOR VARIETY =====
  {
    id: 84,
    reviewType: "5-star",
    industry: "Restaurant",
    tone: "Friendly",
    reviewText: "The new seasonal menu is incredible. Chef really outdid herself this time.",
    responseText: "We'll pass this along to Chef -- she's going to love it! The seasonal menu is her passion project, and she sources ingredients from local farms to make every dish special. So glad you got to experience it. Come back next season to see what she creates next!",
    stars: 5,
  },
  {
    id: 85,
    reviewType: "1-star",
    industry: "Healthcare",
    tone: "Empathetic",
    reviewText: "Was told my insurance was accepted when I called. Got a $400 bill after my visit. Feel deceived.",
    responseText: "We are truly sorry for this billing issue and understand how upsetting it is to receive an unexpected charge. Insurance verification can be complex, and it appears there was a miscommunication. We are committed to resolving this -- please contact our billing team immediately so we can review your coverage and work on a resolution. You should never feel deceived by a healthcare provider.",
    stars: 1,
  },
  {
    id: 86,
    reviewType: "4-star",
    industry: "Home Services",
    tone: "Empathetic",
    reviewText: "Pest control was effective but wish they offered more eco-friendly treatment options.",
    responseText: "We appreciate your feedback and share your concern for the environment. We've been researching and testing eco-friendly pest control alternatives, and we're happy to say we're adding green treatment options to our service lineup soon. We'd love to discuss these options with you for your next treatment. Thank you for pushing us to be better!",
    stars: 4,
  },
  {
    id: 87,
    reviewType: "5-star",
    industry: "Fitness",
    tone: "Professional",
    reviewText: "The personal training program completely transformed my fitness. Lost 40 lbs and gained confidence.",
    responseText: "Thank you for sharing your incredible transformation. A 40-pound journey represents tremendous dedication and discipline on your part. Our personal training team is honored to have played a role in your success. Your results are a testament to the effectiveness of personalized programming and consistent effort. We look forward to supporting your continued fitness journey.",
    stars: 5,
  },
  {
    id: 88,
    reviewType: "2-star",
    industry: "Salon/Spa",
    tone: "Professional",
    reviewText: "Waited 25 minutes past my appointment time with no explanation. Time management needs work.",
    responseText: "We apologize for the delay and for not communicating the reason for the wait. Punctuality is a fundamental part of professional service, and we fell short. We are implementing a new scheduling system to reduce overbooking and ensure clients are seen on time. We value your time and hope to demonstrate that on your next visit.",
    stars: 2,
  },
  {
    id: 89,
    reviewType: "4-star",
    industry: "Auto",
    tone: "Friendly",
    reviewText: "Love that they text you photos of any issues they find. Very transparent.",
    responseText: "That's one of our favorite things too! We think you deserve to see exactly what we see, which is why we send those photos. No guessing, no mystery -- just honest, transparent service. Glad you appreciate it, and we'll keep those updates coming!",
    stars: 4,
  },
  {
    id: 90,
    reviewType: "5-star",
    industry: "SaaS",
    tone: "Professional",
    reviewText: "Migrated our entire team of 200+ people. The onboarding support was world-class.",
    responseText: "Thank you for your confidence in our platform for such a significant migration. Onboarding teams of 200+ requires careful planning and execution, and we are glad our support team was able to facilitate a smooth transition. We are committed to ensuring your entire team gets maximum value from the platform going forward.",
    stars: 5,
  },
  {
    id: 91,
    reviewType: "1-star",
    industry: "SaaS",
    tone: "Empathetic",
    reviewText: "They removed a feature we depended on with zero notice. Our entire workflow is broken.",
    responseText: "We hear your frustration, and we understand how disruptive this is to your workflow. Removing a feature without adequate notice was a mistake on our part, and we take responsibility. Our product team is exploring options to either restore the functionality or provide an alternative solution. Your account manager will reach out within 24 hours to discuss a path forward.",
    stars: 1,
  },
  {
    id: 92,
    reviewType: "5-star",
    industry: "Professional Services",
    tone: "Professional",
    reviewText: "Audit was completed ahead of schedule with zero findings. Best audit experience in our company's history.",
    responseText: "Thank you for your review. Completing the audit ahead of schedule while maintaining thoroughness is a testament to our team's preparation and your organization's excellent practices. We are pleased to have contributed to a smooth and efficient audit process. We look forward to our continued partnership.",
    stars: 5,
  },
  {
    id: 93,
    reviewType: "2-star",
    industry: "Hotel",
    tone: "Professional",
    reviewText: "Pool was closed for maintenance during our stay even though it wasn't mentioned at booking.",
    responseText: "We apologize for not informing you about the pool closure at the time of booking. This is an oversight in our communication process that we are correcting. Guests should always be aware of any amenity limitations before arrival. We would like to offer a partial refund or a discounted future stay to compensate. Please contact our reservations team.",
    stars: 2,
  },
  {
    id: 94,
    reviewType: "4-star",
    industry: "Restaurant",
    tone: "Empathetic",
    reviewText: "Delicious food and great cocktails. Noise level was quite high though, hard to have a conversation.",
    responseText: "We're glad the food and cocktails hit the spot! We know the noise level can be a challenge, especially during peak hours, and we appreciate you mentioning it. We're looking into acoustic solutions to improve the dining experience without losing the energy. In the meantime, our patio seating is a great quieter alternative if available!",
    stars: 4,
  },
  {
    id: 95,
    reviewType: "5-star",
    industry: "Retail",
    tone: "Empathetic",
    reviewText: "Staff helped my elderly mother find everything she needed and even carried bags to her car.",
    responseText: "This truly warms our hearts. We believe in treating every customer like family, and knowing our team went the extra mile for your mother makes us incredibly proud. Everyone deserves a shopping experience where they feel cared for. Please thank your mother for visiting us, and we hope to see you both again soon.",
    stars: 5,
  },
  {
    id: 96,
    reviewType: "3-star",
    industry: "Fitness",
    tone: "Professional",
    reviewText: "Facility is good but the app for booking classes crashes constantly. Please fix it.",
    responseText: "Thank you for your feedback regarding our app. We are aware of the stability issues and our development team is actively working on a major update that addresses the crash reports we've received. We expect the update to be released within the next two weeks. In the meantime, you can book classes through our website or by calling the front desk.",
    stars: 3,
  },
  {
    id: 97,
    reviewType: "5-star",
    industry: "Salon/Spa",
    tone: "Empathetic",
    reviewText: "Been coming here for 5 years and the quality has never dropped. They remember my preferences every time.",
    responseText: "Five years together -- that means the world to us! Building that kind of lasting relationship is what drives our team. Remembering your preferences isn't just good service, it's personal. We genuinely care about every visit being just right for you. Here's to many more years!",
    stars: 5,
  },
  {
    id: 98,
    reviewType: "4-star",
    industry: "Healthcare",
    tone: "Empathetic",
    reviewText: "Excellent pediatrician. My kids actually look forward to their checkups. Just wish parking was easier.",
    responseText: "What a compliment -- getting kids to actually enjoy their doctor visits is no small feat! Dr. and the team work hard to create a welcoming, fun environment for our youngest patients. We hear you on parking and are exploring partnerships with nearby lots to provide more convenient options. Thank you for being part of our practice family!",
    stars: 4,
  },
  {
    id: 99,
    reviewType: "1-star",
    industry: "Home Services",
    tone: "Professional",
    reviewText: "No-showed twice. Both times I took off work to be home. Complete waste of my time.",
    responseText: "We sincerely apologize for the two missed appointments. Your time is valuable, and taking time off work only to have us not show up is unacceptable. We have implemented a new dispatch confirmation system to prevent this from happening. We would like to offer complimentary service and priority scheduling. Please contact our operations manager to arrange this.",
    stars: 1,
  },
  {
    id: 100,
    reviewType: "5-star",
    industry: "Auto",
    tone: "Professional",
    reviewText: "Brought in my classic car and they treated it with the respect it deserves. True craftsmen.",
    responseText: "Thank you for entrusting us with your classic vehicle. Working on classic cars requires specialized knowledge and attention to detail, and our team takes great pride in treating every vehicle with the care it deserves. It is a privilege to help maintain these automotive treasures. We look forward to keeping yours on the road for years to come.",
    stars: 5,
  },
  {
    id: 101,
    reviewType: "2-star",
    industry: "Professional Services",
    tone: "Empathetic",
    reviewText: "Consultant didn't seem familiar with our industry at all. Felt like we were paying to educate them.",
    responseText: "We understand your frustration. When you hire a consultant, you expect expertise from day one, not a learning curve at your expense. This is a valid concern, and we're taking it seriously. We're reviewing our team assignment process to ensure better industry alignment. We'd like to discuss reassigning your project to a consultant with deeper experience in your sector.",
    stars: 2,
  },
  {
    id: 102,
    reviewType: "3-star",
    industry: "Hotel",
    tone: "Friendly",
    reviewText: "Room was nice but checkout process was chaotic. Long lines and confused staff.",
    responseText: "Thanks for the honest feedback! We know a messy checkout can sour an otherwise great stay. We're rolling out express digital checkout so you can check out from your phone -- no lines, no fuss. We'll have this ready soon and think it'll make a world of difference. Hope to see you back!",
    stars: 3,
  },
  {
    id: 103,
    reviewType: "5-star",
    industry: "Retail",
    tone: "Professional",
    reviewText: "The personal shopping service exceeded expectations. Left with a complete wardrobe refresh.",
    responseText: "Thank you for your exceptional review. Our personal shopping service is designed to provide a curated, stress-free experience tailored to each client's style and needs. We are delighted that your wardrobe refresh met your expectations. Our stylists would be happy to assist you again whenever you're ready for your next update.",
    stars: 5,
  },
  {
    id: 104,
    reviewType: "4-star",
    industry: "SaaS",
    tone: "Empathetic",
    reviewText: "Great product, solid support. Only concern is the pace of new features compared to competitors.",
    responseText: "We appreciate your loyalty and the honest feedback. We understand the desire for a faster feature cadence, and we hear this from other users too. We're in the process of expanding our development team to accelerate our roadmap. We'd love to hear your specific feature requests -- they directly influence our priorities. Your input matters!",
    stars: 4,
  },
];
